Repository Int-Byte4/WizBuddy, pull requests merged in 2024-08, with the labels that each got.

#3 ✨ 기능 추가 : CheckList 엔티티 추가
  src/main/java/com/intbyte/wizbuddy/checklist/domain/entity/CheckList.java
Labels: enhancement

#9 ✨ 기능 추가: mybatis config
  src/main/java/com/intbyte/wizbuddy/config/MybatisConfiguration.java
  src/main/java/com/intbyte/wizbuddy/mapper/EmployeeMapper.java
  src/main/java/com/intbyte/wizbuddy/mapper/EmployerMapper.java
  src/main/java/com/intbyte/wizbuddy/shop/domain/entity/Shop.java
Labels: enhancement

#18 ✨ 기능 추가: ShopDTO 추가
  src/main/java/com/intbyte/wizbuddy/shop/dto/ShopDTO.java
Labels: enhancement

#20 ✨ 기능 추가: Mybatis Mapper 추가
  src/main/java/com/intbyte/wizbuddy/mapper/ChecklistMapper.java
  src/main/java/com/intbyte/wizbuddy/mapper/ManualBoardMapper.java
  src/main/java/com/intbyte/wizbuddy/mapper/NoticeBoardMapper.java
  src/main/java/com/intbyte/wizbuddy/mapper/ShopMapper.java
  src/main/java/com/intbyte/wizbuddy/mapper/SubsBoardMapper.java
  src/main/java/com/intbyte/wizbuddy/mapper/TaskMapper.java
  src/main/java/com/intbyte/wizbuddy/mapper/WeeklyScheduleMapper.java
  src/main/resources/com/intbyte/wizbuddy/mapper/ChecklistBoard.xml
  src/main/resources/com/intbyte/wizbuddy/mapper/EmployeeMapper.xml
  src/main/resources/com/intbyte/wizbuddy/mapper/EmployerMapper.xml
  src/main/resources/com/intbyte/wizbuddy/mapper/ManualBoardMapper.xml
  src/main/resources/com/intbyte/wizbuddy/mapper/NoticeBoardMapper.xml
  src/main/resources/com/intbyte/wizbuddy/mapper/ShopMapper.xml
  src/main/resources/com/intbyte/wizbuddy/mapper/SubsBoardMapper.xml
  src/main/resources/com/intbyte/wizbuddy/mapper/TaskMapper.xml
  src/main/resources/com/intbyte/wizbuddy/mapper/WeeklyScheduleMapper.xml
Labels: enhancement

#62 매장 등록, 매장 등록 시 예외처리 추가 및 회원가입 기능 일부 추가
  src/main/java/com/intbyte/wizbuddy/exception/EmailDuplicateException.java
  src/main/java/com/intbyte/wizbuddy/exception/StatusEnum.java
  src/main/java/com/intbyte/wizbuddy/exception/shop/BusinessNumDuplicateException.java
  src/main/java/com/intbyte/wizbuddy/exception/user/EmailDuplicateException.java
  src/main/java/com/intbyte/wizbuddy/exception/user/EmployerNotFoundException.java
  src/main/java/com/intbyte/wizbuddy/mapper/ShopMapper.java
  src/main/java/com/intbyte/wizbuddy/shop/domain/entity/Shop.java
  src/main/java/com/intbyte/wizbuddy/shop/dto/ShopDTO.java
  src/main/java/com/intbyte/wizbuddy/shop/repository/ShopRepository.java
  src/main/java/com/intbyte/wizbuddy/shop/service/ShopService.java
  src/main/java/com/intbyte/wizbuddy/user/domain/entity/Employer.java
  src/main/java/com/intbyte/wizbuddy/user/service/EmployerService.java
  src/main/resources/com/intbyte/wizbuddy/mapper/ShopMapper.xml
  src/test/java/com/intbyte/wizbuddy/shop/service/ShopServiceTests.java
Labels: enhancement

#63 ♻️ 코드 수정 : ShopService 매장등록 코드 수정
  src/main/java/com/intbyte/wizbuddy/shop/service/ShopService.java
Labels: fix

#64 매장 수정 기능 및 테스트 추가
  src/main/java/com/intbyte/wizbuddy/exception/StatusEnum.java
  src/main/java/com/intbyte/wizbuddy/exception/shop/ShopModifyOtherEmployerException.java
  src/main/java/com/intbyte/wizbuddy/exception/shop/ShopNotFoundException.java
  src/main/java/com/intbyte/wizbuddy/shop/domain/EditShopInfo.java
  src/main/java/com/intbyte/wizbuddy/shop/domain/entity/Shop.java
  src/main/java/com/intbyte/wizbuddy/shop/service/ShopService.java
  src/test/java/com/intbyte/wizbuddy/shop/service/ShopServiceTests.java
Labels: enhancement

#65 Kyeong seok
  src/main/java/com/intbyte/wizbuddy/mapper/TaskMapper.java
  src/main/java/com/intbyte/wizbuddy/task/domain/entity/Task.java
  src/main/java/com/intbyte/wizbuddy/task/dto/TaskDTO.java
  src/main/java/com/intbyte/wizbuddy/task/repository/TaskRepository.java
  src/main/java/com/intbyte/wizbuddy/task/service/TaskService.java
  src/main/resources/com/intbyte/wizbuddy/mapper/TaskMapper.xml
  src/test/java/com/intbyte/wizbuddy/task/service/TaskServiceTests.java
Labels: enhancement

#67 ✨ 기능 추가 : 매장 삭제 기능 및 테스트 추가
  src/main/java/com/intbyte/wizbuddy/shop/domain/DeleteShopInfo.java
  src/main/java/com/intbyte/wizbuddy/shop/domain/entity/Shop.java
  src/main/java/com/intbyte/wizbuddy/shop/repository/ShopRepository.java
  src/main/java/com/intbyte/wizbuddy/shop/service/ShopService.java
  src/test/java/com/intbyte/wizbuddy/shop/service/ShopServiceTests.java
Labels: enhancement

#68 ✨ 기능 추가 : 매뉴얼 게시글 등록 기능 추가
  src/main/java/com/intbyte/wizbuddy/board/domain/entity/ManualBoard.java
  src/main/java/com/intbyte/wizbuddy/board/dto/ManualBoardDTO.java
  src/main/java/com/intbyte/wizbuddy/board/repository/ManualBoardRepository.java
  src/main/java/com/intbyte/wizbuddy/board/service/ManualBoardService.java
  src/main/java/com/intbyte/wizbuddy/user/domain/entity/User.java
  src/main/java/com/intbyte/wizbuddy/user/dto/UserDTO.java
  src/main/resources/com/intbyte/wizbuddy/mapper/ManualBoardMapper.xml
  src/test/java/com/intbyte/wizbuddy/board/service/ManualBoardServiceTests.java
Labels: enhancement

#69 업무 로직 수정 및 테스트코드 수정
  src/main/java/com/intbyte/wizbuddy/exception/StatusEnum.java
  src/main/java/com/intbyte/wizbuddy/exception/task/TaskNotFoundException.java
  src/main/java/com/intbyte/wizbuddy/task/domain/EditTaskInfo.java
  src/main/java/com/intbyte/wizbuddy/task/domain/entity/Task.java
  src/main/java/com/intbyte/wizbuddy/task/service/TaskService.java
  src/test/java/com/intbyte/wizbuddy/task/service/TaskServiceTests.java
Labels: enhancement, fix

#70 근무일정 조회 기능 및 테스트 코드 추가 + 등록 기능 추가
  src/main/java/com/intbyte/wizbuddy/exception/weeklyschedule/ScheduleNotFoundException.java
  src/main/java/com/intbyte/wizbuddy/mapper/EmployeeWorkingPartMapper.java
  src/main/java/com/intbyte/wizbuddy/mapper/WeeklyScheduleMapper.java
  src/main/java/com/intbyte/wizbuddy/schedule/domain/entity/EmployeeWorkingPart.java
  src/main/java/com/intbyte/wizbuddy/schedule/domain/entity/WeeklySchedule.java
  src/main/java/com/intbyte/wizbuddy/schedule/dto/EmployeeWorkingPartDTO.java
  src/main/java/com/intbyte/wizbuddy/schedule/repository/EmployeeWorkingPartRepository.java
  src/main/java/com/intbyte/wizbuddy/schedule/repository/WeeklyScheduleRepository.java
  src/main/java/com/intbyte/wizbuddy/schedule/service/ScheduleService.java
  src/main/resources/com/intbyte/wizbuddy/mapper/EmployeeWorkingPartMapper.xml
  src/main/resources/com/intbyte/wizbuddy/mapper/WeeklyScheduleMapper.xml
  src/test/java/com/intbyte/wizbuddy/schedule/service/ScheduleServiceTests.java
Labels: enhancement

#71 유저 외래키 매핑 추가 및 매장 코드 변경
  src/main/java/com/intbyte/wizbuddy/mapper/EmployeeMapper.java
  src/main/java/com/intbyte/wizbuddy/mapper/UserAndEmployerMapper.java
  src/main/java/com/intbyte/wizbuddy/shop/domain/EditShopInfo.java
  src/main/java/com/intbyte/wizbuddy/shop/service/ShopService.java
  src/main/java/com/intbyte/wizbuddy/user/domain/entity/Employee.java
  src/main/resources/com/intbyte/wizbuddy/mapper/EmployeeMapper.xml
  src/main/resources/com/intbyte/wizbuddy/mapper/EmployerMapper.xml
  src/main/resources/com/intbyte/wizbuddy/mapper/ShopMapper.xml
  src/main/resources/com/intbyte/wizbuddy/mapper/UserAndEmployeeMapper.xml
  src/main/resources/com/intbyte/wizbuddy/mapper/UserAndEmployerMapper.xml
  src/test/java/com/intbyte/wizbuddy/shop/service/ShopServiceTests.java
Labels: enhancement

#72 ✨ 기능 추가 : 체크리스트 CRUD 및 테스트코드 추가
  src/main/java/com/intbyte/wizbuddy/checklist/domain/EditCheckListInfo.java
  src/main/java/com/intbyte/wizbuddy/checklist/domain/entity/CheckList.java
  src/main/java/com/intbyte/wizbuddy/checklist/dto/CheckListDTO.java
  src/main/java/com/intbyte/wizbuddy/checklist/repository/CheckListRepository.java
  src/main/java/com/intbyte/wizbuddy/checklist/service/CheckListService.java
  src/main/java/com/intbyte/wizbuddy/exception/StatusEnum.java
  src/main/java/com/intbyte/wizbuddy/exception/checklist/CheckListNotFoundException.java
  src/main/java/com/intbyte/wizbuddy/mapper/CheckListMapper.java
  src/main/java/com/intbyte/wizbuddy/mapper/ChecklistMapper.java
  src/main/java/com/intbyte/wizbuddy/task/service/TaskService.java
  src/main/resources/com/intbyte/wizbuddy/mapper/CheckListMapper.xml
  src/main/resources/com/intbyte/wizbuddy/mapper/ChecklistBoard.xml
  src/test/java/com/intbyte/wizbuddy/checklist/service/CheckListServiceTests.java
  src/test/java/com/intbyte/wizbuddy/task/service/TaskServiceTests.java
Labels: enhancement, fix

#73 매장 조회 기능 추가 및 외래키 매핑 수정
  src/main/java/com/intbyte/wizbuddy/exception/user/UserNotFoundException.java
  src/main/java/com/intbyte/wizbuddy/mapper/EmployerMapper.java
  src/main/java/com/intbyte/wizbuddy/mapper/ShopMapper.java
  src/main/java/com/intbyte/wizbuddy/mapper/UserAndEmployerMapper.java
  src/main/java/com/intbyte/wizbuddy/shop/service/ShopService.java
  src/main/java/com/intbyte/wizbuddy/user/repository/UserRepository.java
  src/main/resources/com/intbyte/wizbuddy/mapper/EmployerMapper.xml
  src/main/resources/com/intbyte/wizbuddy/mapper/ShopMapper.xml
  src/main/resources/com/intbyte/wizbuddy/mapper/UserAndEmployerMapper.xml
  src/test/java/com/intbyte/wizbuddy/shop/service/ShopServiceTests.java
Labels: enhancement, fix

#77 ✨ 기능 추가 : 대타게시판 조회, 등록, 수정, 삭제 기능
  src/main/java/com/intbyte/wizbuddy/board/domain/entity/SubsBoard.java
  src/main/java/com/intbyte/wizbuddy/board/dto/SubsBoardDTO.java
  src/main/java/com/intbyte/wizbuddy/board/repository/SubsBoardRepository.java
  src/main/java/com/intbyte/wizbuddy/board/service/SubsBoardService.java
  src/main/java/com/intbyte/wizbuddy/mapper/SubsBoardMapper.java
  src/main/resources/com/intbyte/wizbuddy/mapper/SubsBoardMapper.xml
  src/test/java/com/intbyte/wizbuddy/board/service/SubsBoardServiceTests.java
Labels: enhancement

#78 ✨ 기능 추가 : 매뉴얼 게시판 게시글 수정, 삭제 기능 추가
  src/main/java/com/intbyte/wizbuddy/board/domain/DeleteManualBoardInfo.java
  src/main/java/com/intbyte/wizbuddy/board/domain/EditManualBoardInfo.java
  src/main/java/com/intbyte/wizbuddy/board/domain/entity/ManualBoard.java
  src/main/java/com/intbyte/wizbuddy/board/domain/entity/NoticeBoard.java
  src/main/java/com/intbyte/wizbuddy/board/dto/ManualBoardDTO.java
  src/main/java/com/intbyte/wizbuddy/board/dto/NoticeBoardDTO.java
  src/main/java/com/intbyte/wizbuddy/board/service/ManualBoardService.java
  src/main/java/com/intbyte/wizbuddy/exception/StatusEnum.java
  src/main/java/com/intbyte/wizbuddy/exception/manualboard/ManualBoardModifyOtherUserException.java
  src/main/java/com/intbyte/wizbuddy/exception/manualboard/ManualBoardNotFoundException.java
  src/main/java/com/intbyte/wizbuddy/mapper/ManualBoardMapper.java
  src/main/resources/com/intbyte/wizbuddy/mapper/ManualBoardMapper.xml
Labels: enhancement

#81 ✨ 기능 추가: 직원별 근무일정 조회, 근무일 수정, 근무일 삭제 및 테스트 코드 추가
  src/main/java/com/intbyte/wizbuddy/mapper/EmployeeWorkingPartMapper.java
  src/main/java/com/intbyte/wizbuddy/mapper/WeeklyScheduleMapper.java
  src/main/java/com/intbyte/wizbuddy/schedule/domain/entity/EmployeeWorkingPart.java
  src/main/java/com/intbyte/wizbuddy/schedule/domain/entity/WeeklySchedule.java
  src/main/java/com/intbyte/wizbuddy/schedule/dto/EmployeeWorkingPartDTO.java
  src/main/java/com/intbyte/wizbuddy/schedule/service/ScheduleService.java
  src/main/resources/com/intbyte/wizbuddy/mapper/EmployeeWorkingPartMapper.xml
  src/main/resources/com/intbyte/wizbuddy/mapper/WeeklyScheduleMapper.xml
  src/test/java/com/intbyte/wizbuddy/schedule/service/ScheduleServiceTests.java
Labels: enhancement

#82 Nahyeon✨ 기능 추가 : Comment 전체 조회 Service, 테스트 기능 추가
  src/main/java/com/intbyte/wizbuddy/comment/domain/Entity/Comment.java
  src/main/java/com/intbyte/wizbuddy/comment/dto/CommentDTO.java
  src/main/java/com/intbyte/wizbuddy/comment/repository/CommentRepository.java
  src/main/java/com/intbyte/wizbuddy/comment/service/CommentService.java
  src/main/java/com/intbyte/wizbuddy/mapper/CommentMapper.java
  src/main/resources/com/intbyte/wizbuddy/mapper/CommentMapper.xml
  src/test/java/com/intbyte/wizbuddy/comment/service/CommentServiceTests.java
Labels: enhancement

#83 ✨ 기능 추가: 스케줄 수정 데이터를 담은 EditScheduleInfo 추가
  src/main/java/com/intbyte/wizbuddy/schedule/domain/EditScheduleInfo.java
Labels: enhancement

#86 Jehun
  src/main/java/com/intbyte/wizbuddy/user/domain/EditEmployeeInfo.java
  src/main/resources/com/intbyte/wizbuddy/mapper/EmployerMapper.xml
  src/test/java/com/intbyte/wizbuddy/user/service/EmployeeServiceTests.java
  src/test/java/com/intbyte/wizbuddy/user/service/EmployerServiceTests.java
Labels: enhancement

#87 ♻️ 코드 수정 : 매장 등록용 info 추가로 인한 코드 수정
  src/main/java/com/intbyte/wizbuddy/shop/domain/RegisterShopInfo.java
  src/main/java/com/intbyte/wizbuddy/shop/service/ShopService.java
  src/test/java/com/intbyte/wizbuddy/shop/service/ShopServiceTests.java
Labels: fix

#88 체크리스트 업무 CRUD 및 테스트코드 완성
  src/main/java/com/intbyte/wizbuddy/mapper/TaskPerCheckListMapper.java
  src/main/java/com/intbyte/wizbuddy/taskperchecklist/domain/EditTaskPerCheckListInfo.java
  src/main/java/com/intbyte/wizbuddy/taskperchecklist/domain/TaskPerCheckListMybatis.java
  src/main/java/com/intbyte/wizbuddy/taskperchecklist/domain/entity/TaskPerCheckList.java
  src/main/java/com/intbyte/wizbuddy/taskperchecklist/domain/entity/TaskPerChecklistId.java
  src/main/java/com/intbyte/wizbuddy/taskperchecklist/service/TaskPerCheckListService.java
  src/main/java/com/intbyte/wizbuddy/user/domain/entity/Employee.java
  src/main/resources/com/intbyte/wizbuddy/mapper/TaskPerCheckListMapper.xml
  src/test/java/com/intbyte/wizbuddy/taskperchecklist/service/TaskPerCheckListServiceTests.java
Labels: bug, enhancement, fix

#90 ✨ 기능 추가: 근무일정에 직원배치 기능 추가 및 테스트코드 수정
  src/main/java/com/intbyte/wizbuddy/schedule/dto/WeeklyScheduleDTO.java
  src/main/java/com/intbyte/wizbuddy/schedule/service/ScheduleService.java
  src/main/resources/com/intbyte/wizbuddy/mapper/WeeklyScheduleMapper.xml
  src/test/java/com/intbyte/wizbuddy/schedule/service/ScheduleServiceTests.java
Labels: enhancement, fix

#91 ♻️ 코드 수정 : Comment 수정 테스트 refactor
  src/main/java/com/intbyte/wizbuddy/board/domain/EditSubsBoardInfo.java
  src/main/java/com/intbyte/wizbuddy/board/domain/entity/SubsBoard.java
  src/main/java/com/intbyte/wizbuddy/board/service/SubsBoardService.java
  src/main/java/com/intbyte/wizbuddy/comment/domain/EditCommentInfo.java
  src/main/java/com/intbyte/wizbuddy/comment/domain/Entity/Comment.java
  src/main/java/com/intbyte/wizbuddy/comment/dto/CommentDTO.java
  src/main/java/com/intbyte/wizbuddy/comment/service/CommentService.java
  src/main/java/com/intbyte/wizbuddy/exception/StatusEnum.java
  src/main/java/com/intbyte/wizbuddy/exception/board/SubsBoardNotFoundException.java
  src/main/java/com/intbyte/wizbuddy/exception/comment/CommentNotFoundException.java
  src/main/java/com/intbyte/wizbuddy/mapper/CommentMapper.java
  src/main/resources/com/intbyte/wizbuddy/mapper/CommentMapper.xml
  src/test/java/com/intbyte/wizbuddy/board/service/SubsBoardServiceTests.java
  src/test/java/com/intbyte/wizbuddy/comment/service/CommentServiceTests.java
Labels: enhancement

#92 UUID, jwt, passwordEncoder 추가를 위해 코드 변경 및 기능 추가
  build.gradle
  src/main/java/com/intbyte/wizbuddy/HMACKeyGenerator.java
  src/main/java/com/intbyte/wizbuddy/config/AppConfig.java
  src/main/java/com/intbyte/wizbuddy/mapper/EmployeeMapper.java
  src/main/java/com/intbyte/wizbuddy/mapper/EmployerMapper.java
  src/main/java/com/intbyte/wizbuddy/shop/domain/DeleteShopInfo.java
  src/main/java/com/intbyte/wizbuddy/shop/domain/EditShopInfo.java
  src/main/java/com/intbyte/wizbuddy/shop/domain/entity/Shop.java
  src/main/java/com/intbyte/wizbuddy/shop/dto/ShopDTO.java
  src/main/java/com/intbyte/wizbuddy/shop/service/ShopService.java
  src/main/java/com/intbyte/wizbuddy/user/UserTypeEnum.java
  src/main/java/com/intbyte/wizbuddy/user/domain/DeleteEmployeeInfo.java
  src/main/java/com/intbyte/wizbuddy/user/domain/DeleteEmployerInfo.java
  src/main/java/com/intbyte/wizbuddy/user/domain/EditEmployeeInfo.java
  src/main/java/com/intbyte/wizbuddy/user/domain/EditEmployerInfo.java
  src/main/java/com/intbyte/wizbuddy/user/domain/RegisterEmployeeInfo.java
  src/main/java/com/intbyte/wizbuddy/user/domain/RegisterEmployerInfo.java
  src/main/java/com/intbyte/wizbuddy/user/domain/SignInUserInfo.java
  src/main/java/com/intbyte/wizbuddy/user/domain/entity/Employee.java
  src/main/java/com/intbyte/wizbuddy/user/domain/entity/Employer.java
  src/main/java/com/intbyte/wizbuddy/user/domain/entity/User.java
  src/main/java/com/intbyte/wizbuddy/user/dto/EmployeeDTO.java
  src/main/java/com/intbyte/wizbuddy/user/dto/EmployerDTO.java
  src/main/java/com/intbyte/wizbuddy/user/dto/UserDTO.java
  src/main/java/com/intbyte/wizbuddy/user/service/EmployeeService.java
  src/main/java/com/intbyte/wizbuddy/user/service/EmployerService.java
  src/main/java/com/intbyte/wizbuddy/user/service/UserService.java
  src/main/resources/com/intbyte/wizbuddy/mapper/EmployeeMapper.xml
  src/main/resources/com/intbyte/wizbuddy/mapper/EmployerMapper.xml
  src/main/resources/com/intbyte/wizbuddy/mapper/UserAndEmployeeMapper.xml
  src/main/resources/com/intbyte/wizbuddy/mapper/UserAndEmployerMapper.xml
  src/test/java/com/intbyte/wizbuddy/shop/service/ShopServiceTests.java
  src/test/java/com/intbyte/wizbuddy/user/service/EmployeeServiceTests.java
  src/test/java/com/intbyte/wizbuddy/user/service/EmployerServiceTests.java
  src/test/java/com/intbyte/wizbuddy/user/service/UserServiceTests.java
Labels: enhancement

#93 ✨ 기능 추가: user id가 String으로 바뀌는 과정에서 Task, CheckList, TaskPerCheckList관련 코드 수정 및 조회 테스트 추가 수행
  src/main/java/com/intbyte/wizbuddy/checklist/service/CheckListService.java
  src/main/java/com/intbyte/wizbuddy/exception/StatusEnum.java
  src/main/java/com/intbyte/wizbuddy/exception/taskperchecklist/TaskPerCheckListNotFoundException.java
  src/main/java/com/intbyte/wizbuddy/mapper/CheckListMapper.java
  src/main/java/com/intbyte/wizbuddy/mapper/TaskMapper.java
  src/main/java/com/intbyte/wizbuddy/mapper/TaskPerCheckListMapper.java
  src/main/java/com/intbyte/wizbuddy/task/service/TaskService.java
  src/main/java/com/intbyte/wizbuddy/taskperchecklist/domain/EditTaskPerCheckListInfo.java
  src/main/java/com/intbyte/wizbuddy/taskperchecklist/domain/TaskPerCheckListMybatis.java
  src/main/java/com/intbyte/wizbuddy/taskperchecklist/dto/TaskPerCheckListDTO.java
  src/main/java/com/intbyte/wizbuddy/taskperchecklist/service/TaskPerCheckListService.java
  src/main/java/com/intbyte/wizbuddy/user/repository/EmployeeRepository.java
  src/main/resources/com/intbyte/wizbuddy/mapper/CheckListMapper.xml
  src/main/resources/com/intbyte/wizbuddy/mapper/TaskMapper.xml
  src/main/resources/com/intbyte/wizbuddy/mapper/TaskPerCheckListMapper.xml
  src/test/java/com/intbyte/wizbuddy/checklist/service/CheckListServiceTests.java
  src/test/java/com/intbyte/wizbuddy/task/service/TaskServiceTests.java
  src/test/java/com/intbyte/wizbuddy/taskperchecklist/service/TaskPerCheckListServiceTests.java
Labels: bug, enhancement, fix

#94 ✨ 기능 추가: 근무일정 기능 별 예외처리 추가
  src/main/java/com/intbyte/wizbuddy/comment/service/CommentService.java
  src/main/java/com/intbyte/wizbuddy/exception/StatusEnum.java
  src/main/java/com/intbyte/wizbuddy/exception/schedule/EmployeeCodeNotFoundException.java
  src/main/java/com/intbyte/wizbuddy/exception/schedule/ScheduleCodeDuplicateException.java
  src/main/java/com/intbyte/wizbuddy/exception/schedule/ScheduleNotFoundException.java
  src/main/java/com/intbyte/wizbuddy/mapper/EmployeeWorkingPartMapper.java
  src/main/java/com/intbyte/wizbuddy/mapper/WeeklyScheduleMapper.java
  src/main/java/com/intbyte/wizbuddy/schedule/domain/entity/WeeklySchedule.java
  src/main/java/com/intbyte/wizbuddy/schedule/dto/WeeklyScheduleDTO.java
  src/main/java/com/intbyte/wizbuddy/schedule/repository/WeeklyScheduleRepository.java
  src/main/java/com/intbyte/wizbuddy/schedule/service/ScheduleService.java
  src/main/resources/com/intbyte/wizbuddy/mapper/EmployeeWorkingPartMapper.xml
  src/main/resources/com/intbyte/wizbuddy/mapper/WeeklyScheduleMapper.xml
  src/test/java/com/intbyte/wizbuddy/schedule/service/ScheduleServiceTests.java
Labels: enhancement, fix
