Repository Int-Byte4/WizBuddy, pull requests merged in 2024-09, with the labels that each got.

#98 ✨ 기능 추가: 대타 게시판에서 댓글 선택해서 근무일정 수정 기능 추가
  src/main/java/com/intbyte/wizbuddy/mapper/EmployeeWorkingPartMapper.java
  src/main/java/com/intbyte/wizbuddy/schedule/repository/EmployeeWorkingPartRepository.java
  src/main/java/com/intbyte/wizbuddy/schedule/service/ScheduleService.java
  src/main/resources/com/intbyte/wizbuddy/mapper/EmployeeWorkingPartMapper.xml
  src/test/java/com/intbyte/wizbuddy/schedule/service/ScheduleServiceTests.java
Labels: enhancement

#100 ✨ 기능 추가 / 수정 CheckList 외래키 제약조건 추가
  src/main/java/com/intbyte/wizbuddy/checklist/domain/CheckListMybatis.java
  src/main/java/com/intbyte/wizbuddy/checklist/domain/entity/CheckList.java
  src/main/java/com/intbyte/wizbuddy/checklist/service/CheckListService.java
  src/main/java/com/intbyte/wizbuddy/mapper/CheckListMapper.java
  src/main/resources/com/intbyte/wizbuddy/mapper/CheckListMapper.xml
  src/test/java/com/intbyte/wizbuddy/checklist/service/CheckListServiceTests.java
Labels: fix

#101 ♻ 코드 수정: 체크리스트 엔티티 어노테이션 수정
  src/main/java/com/intbyte/wizbuddy/checklist/domain/entity/CheckList.java
Labels: fix

#102 ♻️ 코드 수정 : Comment Type 변환 수정
  src/main/java/com/intbyte/wizbuddy/comment/domain/Entity/Comment.java
  src/main/java/com/intbyte/wizbuddy/comment/dto/CommentDTO.java
  src/test/java/com/intbyte/wizbuddy/comment/service/CommentServiceTests.java
Labels: enhancement

#103 시큐리티 적용 - 회원가입, 로그인, 사장 조회 기능 추가
  src/main/java/com/intbyte/wizbuddy/mapper/UserAndEmployeeMapper.java
  src/main/java/com/intbyte/wizbuddy/mapper/UserAndEmployerMapper.java
  src/main/java/com/intbyte/wizbuddy/security/AuthenticationFilter.java
  src/main/java/com/intbyte/wizbuddy/security/JwtFilter.java
  src/main/java/com/intbyte/wizbuddy/security/JwtUtil.java
  src/main/java/com/intbyte/wizbuddy/security/WebSecurity.java
  src/main/java/com/intbyte/wizbuddy/user/controller/UserController.java
  src/main/java/com/intbyte/wizbuddy/user/service/EmployerService.java
  src/main/java/com/intbyte/wizbuddy/user/service/UserService.java
  src/main/java/com/intbyte/wizbuddy/user/service/UserServiceImpl.java
  src/main/java/com/intbyte/wizbuddy/user/vo/request/RegisterEmployeeRequest.java
  src/main/java/com/intbyte/wizbuddy/user/vo/request/RegisterEmployerRequest.java
  src/main/java/com/intbyte/wizbuddy/user/vo/request/RequestLoginVO.java
  src/main/java/com/intbyte/wizbuddy/user/vo/request/RequestRegisterEmployeeVO.java
  src/main/java/com/intbyte/wizbuddy/user/vo/request/RequestRegisterEmployerVO.java
  src/main/java/com/intbyte/wizbuddy/user/vo/request/RequestRegisterUserVO.java
  src/main/java/com/intbyte/wizbuddy/user/vo/response/ResponseFindEmployeeVO.java
  src/main/java/com/intbyte/wizbuddy/user/vo/response/ResponseFindEmployerVO.java
  src/main/java/com/intbyte/wizbuddy/user/vo/response/ResponseFindUserVO.java
  src/main/java/com/intbyte/wizbuddy/user/vo/response/ResponseRegisterEmployeeVO.java
  src/main/java/com/intbyte/wizbuddy/user/vo/response/ResponseRegisterEmployerVO.java
  src/main/java/com/intbyte/wizbuddy/vo/request/RegisterEmployerRequest.java
  src/main/java/com/intbyte/wizbuddy/vo/request/RequestLoginVO.java
  src/main/java/com/intbyte/wizbuddy/vo/response/ResponseRegisterEmployeeVO.java
  src/main/resources/com/intbyte/wizbuddy/mapper/UserAndEmployeeMapper.xml
  src/main/resources/com/intbyte/wizbuddy/mapper/UserAndEmployerMapper.xml
Labels: enhancement

#105 ✨ 기능 추가 : 매장별 대타게시글 모두 조회 테스트 기능 추가
  src/main/java/com/intbyte/wizbuddy/board/service/SubsBoardService.java
  src/main/java/com/intbyte/wizbuddy/comment/service/CommentService.java
  src/main/java/com/intbyte/wizbuddy/exception/board/SubsBoardNotFoundException.java
  src/main/java/com/intbyte/wizbuddy/mapper/CommentMapper.java
  src/main/java/com/intbyte/wizbuddy/mapper/SubsBoardMapper.java
  src/main/resources/com/intbyte/wizbuddy/mapper/CommentMapper.xml
  src/main/resources/com/intbyte/wizbuddy/mapper/SubsBoardMapper.xml
  src/test/java/com/intbyte/wizbuddy/board/service/SubsBoardServiceTests.java
  src/test/java/com/intbyte/wizbuddy/comment/service/CommentServiceTests.java
Labels: enhancement, fix

#106 ✨ 기능 추가 : Comment 채택 기능 추가
  src/main/java/com/intbyte/wizbuddy/board/domain/entity/SubsBoard.java
  src/main/java/com/intbyte/wizbuddy/comment/domain/Entity/Comment.java
  src/main/java/com/intbyte/wizbuddy/comment/service/CommentService.java
  src/test/java/com/intbyte/wizbuddy/comment/service/CommentServiceTests.java
Labels: enhancement, fix

#107 ✨ 기능 추가: Task Controller 추가
  src/main/java/com/intbyte/wizbuddy/task/controller/TaskController.java
  src/main/java/com/intbyte/wizbuddy/task/dto/TaskDTO.java
  src/main/java/com/intbyte/wizbuddy/task/vo/response/ResponseFindTaskVO.java
Labels: enhancement

#108 ✨ 기능 추가: TaskController 매핑 완료
  src/main/java/com/intbyte/wizbuddy/security/WebSecurity.java
  src/main/java/com/intbyte/wizbuddy/task/controller/TaskController.java
  src/main/java/com/intbyte/wizbuddy/task/domain/EditTaskInfo.java
  src/main/java/com/intbyte/wizbuddy/task/vo/request/RequestInsertTaskVO.java
  src/main/java/com/intbyte/wizbuddy/task/vo/request/RequestModifyTaskVO.java
  src/main/java/com/intbyte/wizbuddy/task/vo/response/ResponseInsertTaskVO.java
  src/main/java/com/intbyte/wizbuddy/task/vo/response/ResponseModifyTaskVO.java
Labels: enhancement

#109 ✨ 기능 추가 : 직원 조회 기능 추가 및 테스트코드 수정
  src/main/java/com/intbyte/wizbuddy/user/controller/UserController.java
  src/main/java/com/intbyte/wizbuddy/user/service/EmployeeService.java
  src/test/java/com/intbyte/wizbuddy/shop/service/ShopServiceTests.java
  src/test/java/com/intbyte/wizbuddy/user/service/EmployeeServiceTests.java
  src/test/java/com/intbyte/wizbuddy/user/service/EmployerServiceTests.java
  src/test/java/com/intbyte/wizbuddy/user/service/UserServiceImplTests.java
Labels: enhancement

#110 ✨ 기능 추가 : 직원 추가, 조회 컨트롤러 추가
  src/main/java/com/intbyte/wizbuddy/user/controller/UserController.java
  src/main/java/com/intbyte/wizbuddy/user/service/EmployeeService.java
  src/main/java/com/intbyte/wizbuddy/user/service/EmployerService.java
  src/main/java/com/intbyte/wizbuddy/user/service/UserServiceImpl.java
Labels: enhancement

#111 ✨ 기능 추가: 공지사항 게시글 좋아요, 매뉴얼 게시글 좋아요 기능 및 테스트코드 추가
  src/main/java/com/intbyte/wizbuddy/board/domain/entity/ManualBoardLiked.java
  src/main/java/com/intbyte/wizbuddy/board/domain/entity/NoticeBoardLiked.java
  src/main/java/com/intbyte/wizbuddy/board/dto/ManualBoardLikedDTO.java
  src/main/java/com/intbyte/wizbuddy/board/dto/NoticeBoardLikedDTO.java
  src/main/java/com/intbyte/wizbuddy/board/repository/ManualBoardLikedRepository.java
  src/main/java/com/intbyte/wizbuddy/board/repository/NoticeBoardLikedRepository.java
  src/main/java/com/intbyte/wizbuddy/board/service/ManualBoardLikedService.java
  src/main/java/com/intbyte/wizbuddy/board/service/NoticeBoardLikedService.java
  src/main/java/com/intbyte/wizbuddy/mapper/ManualBoardLikedMapper.java
  src/main/java/com/intbyte/wizbuddy/mapper/NoticeBoardLikedMapper.java
  src/main/resources/com/intbyte/wizbuddy/mapper/ManualBoardLikedMapper.xml
  src/main/resources/com/intbyte/wizbuddy/mapper/NoticeBoardLikedMapper.xml
  src/test/java/com/intbyte/wizbuddy/board/service/ManualBoardLikedServiceTests.java
  src/test/java/com/intbyte/wizbuddy/board/service/NoticeBoardLikedServiceTests.java
Labels: enhancement

#113 ♻ 코드 수정: employeeCode 타입 변경 및 관련 서비스 기능 코드 수정
  src/main/java/com/intbyte/wizbuddy/mapper/EmployeeWorkingPartMapper.java
  src/main/java/com/intbyte/wizbuddy/schedule/domain/EditScheduleInfo.java
  src/main/java/com/intbyte/wizbuddy/schedule/domain/entity/EmployeeWorkingPart.java
  src/main/java/com/intbyte/wizbuddy/schedule/dto/EmployeeWorkingPartDTO.java
  src/main/java/com/intbyte/wizbuddy/schedule/service/ScheduleService.java
  src/main/resources/com/intbyte/wizbuddy/mapper/EmployeeWorkingPartMapper.xml
  src/test/java/com/intbyte/wizbuddy/schedule/service/ScheduleServiceTests.java
Labels: fix

#114 ✨ 기능 추가 : SubsBoard Controller 추가
  src/main/java/com/intbyte/wizbuddy/board/controller/SubsBoardController.java
  src/main/java/com/intbyte/wizbuddy/board/domain/entity/SubsBoard.java
  src/main/java/com/intbyte/wizbuddy/board/vo/request/RequestDeleteSubsBoardVO.java
  src/main/java/com/intbyte/wizbuddy/board/vo/request/RequestInsertSubsBoardVO.java
  src/main/java/com/intbyte/wizbuddy/board/vo/request/RequestModifySubsBoardVO.java
  src/main/java/com/intbyte/wizbuddy/board/vo/response/ResponseDeleteSubsBoardVO.java
  src/main/java/com/intbyte/wizbuddy/board/vo/response/ResponseFindSubsBoardVO.java
  src/main/java/com/intbyte/wizbuddy/board/vo/response/ResponseInsertSubsBoardVO.java
  src/main/java/com/intbyte/wizbuddy/board/vo/response/ResponseModifySubsBoardVO.java
  src/main/java/com/intbyte/wizbuddy/comment/domain/Entity/Comment.java
Labels: enhancement, fix

#115 공지사항, 매뉴얼 게시글 전체 조회, 단건 조회 기능 및 테스트코드 추가
  src/main/java/com/intbyte/wizbuddy/board/dto/NoticeBoardDTO.java
  src/main/java/com/intbyte/wizbuddy/board/service/ManualBoardService.java
  src/main/java/com/intbyte/wizbuddy/board/service/NoticeBoardService.java
  src/main/java/com/intbyte/wizbuddy/mapper/ManualBoardMapper.java
  src/main/java/com/intbyte/wizbuddy/mapper/NoticeBoardMapper.java
  src/main/resources/com/intbyte/wizbuddy/mapper/ManualBoardMapper.xml
  src/main/resources/com/intbyte/wizbuddy/mapper/NoticeBoardMapper.xml
  src/test/java/com/intbyte/wizbuddy/board/service/ManualBoardServiceTests.java
  src/test/java/com/intbyte/wizbuddy/board/service/NoticeBoardServiceTests.java
Labels: enhancement

#119 ♻️ 코드 수정 : TaskPerCheckListService 코드 수정
  src/main/java/com/intbyte/wizbuddy/checklist/service/CheckListService.java
  src/main/java/com/intbyte/wizbuddy/taskperchecklist/service/TaskPerCheckListService.java
  src/test/java/com/intbyte/wizbuddy/taskperchecklist/service/TaskPerCheckListServiceTests.java
Labels: fix

#121 매뉴얼 게시판 controller, vo 추가 및 전체 조회 기능 코드 수정
  src/main/java/com/intbyte/wizbuddy/board/controller/ManualBoardController.java
  src/main/java/com/intbyte/wizbuddy/board/controller/NoticeBoardController.java
  src/main/java/com/intbyte/wizbuddy/board/service/ManualBoardService.java
  src/main/java/com/intbyte/wizbuddy/board/vo/response/ResponseFindManualBoardVO.java
  src/main/java/com/intbyte/wizbuddy/mapper/ManualBoardMapper.java
  src/main/java/com/intbyte/wizbuddy/security/WebSecurity.java
  src/main/resources/com/intbyte/wizbuddy/mapper/ManualBoardMapper.xml
  src/test/java/com/intbyte/wizbuddy/board/service/ManualBoardServiceTests.java
Labels: enhancement, fix

#122 ✨ 기능 추가: TaskPerCheckListService 예외처리 전 최종 푸시
  src/main/java/com/intbyte/wizbuddy/security/WebSecurity.java
  src/main/java/com/intbyte/wizbuddy/taskperchecklist/controller/TaskPerCheckListController.java
  src/main/java/com/intbyte/wizbuddy/taskperchecklist/domain/EditTaskPerCheckListInfo.java
  src/main/java/com/intbyte/wizbuddy/taskperchecklist/service/TaskPerCheckListService.java
  src/main/java/com/intbyte/wizbuddy/taskperchecklist/vo/request/RequestInsertTaskPerCheckListVO.java
  src/main/java/com/intbyte/wizbuddy/taskperchecklist/vo/request/RequestModifyTaskPerCheckListVO.java
  src/test/java/com/intbyte/wizbuddy/checklist/service/CheckListServiceTests.java
  src/test/java/com/intbyte/wizbuddy/task/service/TaskServiceTests.java
  src/test/java/com/intbyte/wizbuddy/taskperchecklist/service/TaskPerCheckListServiceTests.java
Labels: enhancement

#123 ✨ 기능 추가 : SubsBoard 조회,등록,수정,삭제 api 경로 및 권한 최종완료
  src/main/java/com/intbyte/wizbuddy/board/controller/SubsBoardController.java
  src/main/java/com/intbyte/wizbuddy/board/service/SubsBoardService.java
  src/main/java/com/intbyte/wizbuddy/board/vo/request/RequestDeleteSubsBoardVO.java
  src/main/java/com/intbyte/wizbuddy/board/vo/request/RequestInsertSubsBoardVO.java
  src/main/java/com/intbyte/wizbuddy/board/vo/request/RequestModifySubsBoardVO.java
  src/main/java/com/intbyte/wizbuddy/board/vo/response/ResponseDeleteSubsBoardVO.java
  src/main/java/com/intbyte/wizbuddy/board/vo/response/ResponseInsertSubsBoardVO.java
  src/main/java/com/intbyte/wizbuddy/board/vo/response/ResponseModifySubsBoardVO.java
  src/main/java/com/intbyte/wizbuddy/security/WebSecurity.java
Labels: enhancement, fix

#125 ✨ 기능 추가 : 매장 별 직원 - 직원이 속한 매장 조회 및 매장 별 직원 삭제 추가
  src/main/java/com/intbyte/wizbuddy/common/CommonResponse.java
  src/main/java/com/intbyte/wizbuddy/employeepershop/controller/EmployeePerShopController.java
  src/main/java/com/intbyte/wizbuddy/employeepershop/domain/EmployeePerShopMybatis.java
  src/main/java/com/intbyte/wizbuddy/employeepershop/service/EmployeePerShopService.java
  src/main/java/com/intbyte/wizbuddy/mapper/EmployeePerShopMapper.java
  src/main/java/com/intbyte/wizbuddy/mapper/ShopMapper.java
  src/main/java/com/intbyte/wizbuddy/security/WebSecurity.java
  src/main/java/com/intbyte/wizbuddy/user/repository/EmployerRepository.java
  src/main/java/com/intbyte/wizbuddy/user/service/UserService.java
  src/main/java/com/intbyte/wizbuddy/user/service/UserServiceImpl.java
  src/main/resources/com/intbyte/wizbuddy/mapper/EmployeePerShopMapper.xml
  src/main/resources/com/intbyte/wizbuddy/mapper/ShopMapper.xml
  src/test/java/com/intbyte/wizbuddy/employeepershop/service/EmployeePerShopServiceTests.java
Labels: enhancement

#126 ✨ 기능 추가 Task, CheckList, TaskperCheckList 최종 수정
  src/main/java/com/intbyte/wizbuddy/checklist/controller/CheckListController.java
  src/main/java/com/intbyte/wizbuddy/checklist/domain/CheckListMybatis.java
  src/main/java/com/intbyte/wizbuddy/checklist/domain/EditCheckListInfo.java
  src/main/java/com/intbyte/wizbuddy/checklist/dto/CheckListDTO.java
  src/main/java/com/intbyte/wizbuddy/checklist/service/CheckListService.java
  src/main/java/com/intbyte/wizbuddy/checklist/vo/request/RequestModifyCheckListVO.java
  src/main/java/com/intbyte/wizbuddy/exception/StatusEnum.java
  src/main/java/com/intbyte/wizbuddy/exception/schedule/EmployeeCodeNotFoundException.java
  src/main/java/com/intbyte/wizbuddy/exception/user/EmployeeNotFoundException.java
  src/main/java/com/intbyte/wizbuddy/task/controller/TaskController.java
  src/main/java/com/intbyte/wizbuddy/task/domain/EditTaskInfo.java
  src/main/java/com/intbyte/wizbuddy/task/service/TaskService.java
  src/main/java/com/intbyte/wizbuddy/taskperchecklist/controller/TaskPerCheckListController.java
  src/main/java/com/intbyte/wizbuddy/taskperchecklist/domain/entity/TaskPerCheckList.java
  src/main/java/com/intbyte/wizbuddy/taskperchecklist/service/TaskPerCheckListService.java
  src/main/resources/com/intbyte/wizbuddy/mapper/CheckListMapper.xml
  src/main/resources/com/intbyte/wizbuddy/mapper/TaskMapper.xml
  src/main/resources/com/intbyte/wizbuddy/mapper/TaskPerCheckListMapper.xml
  src/test/java/com/intbyte/wizbuddy/checklist/service/CheckListServiceTests.java
  src/test/java/com/intbyte/wizbuddy/taskperchecklist/service/TaskPerCheckListServiceTests.java
Labels: bug, enhancement, fix

#127 ♻ 코드 수정: ManyToOne 관계 제거
  src/main/java/com/intbyte/wizbuddy/employeepershop/controller/EmployeePerShopController.java
  src/main/java/com/intbyte/wizbuddy/employeepershop/domain/entity/EmployeePerShop.java
  src/main/java/com/intbyte/wizbuddy/employeepershop/domain/entity/EmployeePerShopId.java
  src/main/java/com/intbyte/wizbuddy/employeepershop/repository/EmployeePerShopRepository.java
  src/main/java/com/intbyte/wizbuddy/employeepershop/service/EmployeePerShopService.java
  src/main/java/com/intbyte/wizbuddy/mapper/EmployeePerShopMapper.java
  src/main/java/com/intbyte/wizbuddy/mapper/ShopMapper.java
  src/main/java/com/intbyte/wizbuddy/security/WebSecurity.java
  src/main/java/com/intbyte/wizbuddy/user/service/UserServiceImpl.java
  src/main/resources/com/intbyte/wizbuddy/mapper/EmployeePerShopMapper.xml
  src/main/resources/com/intbyte/wizbuddy/mapper/ShopMapper.xml
  src/test/java/com/intbyte/wizbuddy/employeepershop/service/EmployeePerShopServiceTests.java
Labels: fix

#128 ✨ 기능 추가: 댓글 채택해서 스케줄 수정 기능 추가
  src/main/java/com/intbyte/wizbuddy/board/repository/SubsBoardRepository.java
  src/main/java/com/intbyte/wizbuddy/comment/repository/CommentRepository.java
  src/main/java/com/intbyte/wizbuddy/mapper/EmployeeWorkingPartMapper.java
  src/main/java/com/intbyte/wizbuddy/mapper/WeeklyScheduleMapper.java
  src/main/java/com/intbyte/wizbuddy/schedule/controller/ScheduleController.java
  src/main/java/com/intbyte/wizbuddy/schedule/domain/entity/EmployeeWorkingPart.java
  src/main/java/com/intbyte/wizbuddy/schedule/domain/entity/WeeklySchedule.java
  src/main/java/com/intbyte/wizbuddy/schedule/info/EditScheduleInfo.java
  src/main/java/com/intbyte/wizbuddy/schedule/repository/EmployeeWorkingPartRepository.java
  src/main/java/com/intbyte/wizbuddy/schedule/service/ScheduleService.java
  src/main/java/com/intbyte/wizbuddy/schedule/vo/response/ResponseFindEmployeeWorkingPartVO.java
  src/main/java/com/intbyte/wizbuddy/security/WebSecurity.java
  src/main/resources/com/intbyte/wizbuddy/mapper/EmployeeWorkingPartMapper.xml
  src/main/resources/com/intbyte/wizbuddy/mapper/WeeklyScheduleMapper.xml
  src/test/java/com/intbyte/wizbuddy/schedule/service/ScheduleServiceTests.java
Labels: enhancement

#130 ✨ 기능 추가 : 매뉴얼 게시판 controller 추가
  src/main/java/com/intbyte/wizbuddy/board/controller/ManualBoardController.java
  src/main/java/com/intbyte/wizbuddy/board/domain/DeleteManualBoardInfo.java
  src/main/java/com/intbyte/wizbuddy/board/domain/EditManualBoardInfo.java
  src/main/java/com/intbyte/wizbuddy/board/domain/entity/ManualBoard.java
  src/main/java/com/intbyte/wizbuddy/board/dto/ManualBoardDTO.java
  src/main/java/com/intbyte/wizbuddy/board/service/ManualBoardService.java
  src/main/java/com/intbyte/wizbuddy/board/vo/request/RequestInsertManualBoardVO.java
  src/main/java/com/intbyte/wizbuddy/board/vo/request/RequestUpdateManualBoardVO.java
  src/main/java/com/intbyte/wizbuddy/board/vo/response/ResponseFindManualBoardVO.java
  src/main/java/com/intbyte/wizbuddy/board/vo/response/ResponseInsertManualBoardVO.java
  src/main/java/com/intbyte/wizbuddy/board/vo/response/ResponseUpdateManualBoardVO.java
  src/main/java/com/intbyte/wizbuddy/mapper/ManualBoardMapper.java
  src/main/java/com/intbyte/wizbuddy/security/WebSecurity.java
  src/main/resources/com/intbyte/wizbuddy/mapper/ManualBoardMapper.xml
  src/test/java/com/intbyte/wizbuddy/board/service/ManualBoardServiceTests.java
Labels: enhancement

#131 Nahyeon✨ 기능 추가 : Comment 조회,등록,수정,삭제 api 경로 및 권한 추가
  src/main/java/com/intbyte/wizbuddy/comment/controller/CommentController.java
  src/main/java/com/intbyte/wizbuddy/comment/service/CommentService.java
  src/main/java/com/intbyte/wizbuddy/comment/vo/request/RequestAdoptCommentVO.java
  src/main/java/com/intbyte/wizbuddy/comment/vo/request/RequestDeleteCommentVO.java
  src/main/java/com/intbyte/wizbuddy/comment/vo/request/RequestInsertCommentVO.java
  src/main/java/com/intbyte/wizbuddy/comment/vo/request/RequestModifyCommentVO.java
  src/main/java/com/intbyte/wizbuddy/comment/vo/response/ResponseAdoptCommentVO.java
  src/main/java/com/intbyte/wizbuddy/comment/vo/response/ResponseDeleteCommentVO.java
  src/main/java/com/intbyte/wizbuddy/comment/vo/response/ResponseFindCommentVO.java
  src/main/java/com/intbyte/wizbuddy/comment/vo/response/ResponseInsertCommentVO.java
  src/main/java/com/intbyte/wizbuddy/comment/vo/response/ResponseModifyCommentVO.java
  src/main/java/com/intbyte/wizbuddy/exception/checklist/CheckListNotFoundException.java
  src/main/java/com/intbyte/wizbuddy/security/WebSecurity.java
Labels: enhancement, fix

#132 ✨ 기능 추가: ScheduleController에 댓글 채택으로 스케줄 수정 기능 추가
  src/main/java/com/intbyte/wizbuddy/schedule/controller/ScheduleController.java
  src/main/java/com/intbyte/wizbuddy/schedule/service/ScheduleService.java
  src/main/java/com/intbyte/wizbuddy/schedule/vo/request/RequestModifyScheduleByCommentVO.java
  src/main/java/com/intbyte/wizbuddy/schedule/vo/response/ResponseModifyScheduleByCommentVO.java
  src/main/java/com/intbyte/wizbuddy/security/WebSecurity.java
  src/test/java/com/intbyte/wizbuddy/schedule/service/ScheduleServiceTests.java
Labels: enhancement

#133 ✨ 기능 수정 : 게시글 좋아요 기능 수정
  src/main/java/com/intbyte/wizbuddy/like/domain/entity/ManualBoardLiked.java
  src/main/java/com/intbyte/wizbuddy/like/domain/entity/NoticeBoardLiked.java
  src/main/java/com/intbyte/wizbuddy/like/dto/ManualBoardLikedDTO.java
  src/main/java/com/intbyte/wizbuddy/like/dto/NoticeBoardLikedDTO.java
  src/main/java/com/intbyte/wizbuddy/like/repository/ManualBoardLikedRepository.java
  src/main/java/com/intbyte/wizbuddy/like/repository/NoticeBoardLikedRepository.java
  src/main/java/com/intbyte/wizbuddy/like/service/ManualBoardLikedService.java
  src/main/java/com/intbyte/wizbuddy/like/service/NoticeBoardLikedService.java
  src/main/resources/com/intbyte/wizbuddy/mapper/ManualBoardLikedMapper.xml
  src/main/resources/com/intbyte/wizbuddy/mapper/NoticeBoardLikedMapper.xml
  src/test/java/com/intbyte/wizbuddy/board/service/ManualBoardLikedServiceTests.java
  src/test/java/com/intbyte/wizbuddy/board/service/NoticeBoardLikedServiceTests.java
Labels: enhancement, fix

#135 ✨ 기능 추가 : Like 등록 요청, 응답 RestAPI 기능 추가
  src/main/java/com/intbyte/wizbuddy/board/controller/SubsBoardController.java
  src/main/java/com/intbyte/wizbuddy/board/vo/request/RequestInsertManualBoardVO.java
  src/main/java/com/intbyte/wizbuddy/board/vo/request/RequestInsertSubsBoardVO.java
  src/main/java/com/intbyte/wizbuddy/board/vo/request/RequestModifySubsBoardVO.java
  src/main/java/com/intbyte/wizbuddy/like/controller/ManualBoardLikeController.java
  src/main/java/com/intbyte/wizbuddy/like/controller/NoticeBoardLikeController.java
  src/main/java/com/intbyte/wizbuddy/like/domain/entity/ManualBoardLiked.java
  src/main/java/com/intbyte/wizbuddy/like/domain/entity/NoticeBoardLiked.java
  src/main/java/com/intbyte/wizbuddy/like/service/ManualBoardLikedService.java
  src/main/java/com/intbyte/wizbuddy/like/service/NoticeBoardLikedService.java
  src/main/java/com/intbyte/wizbuddy/like/vo/request/RequestInsertManualBoardLikeVO.java
  src/main/java/com/intbyte/wizbuddy/like/vo/request/RequestInsertNoticeBoardLikeVO.java
  src/main/java/com/intbyte/wizbuddy/like/vo/response/ResponseInsertManualBoardLikeVO.java
  src/main/java/com/intbyte/wizbuddy/like/vo/response/ResponseInsertNoticeBoardLikeVO.java
  src/main/java/com/intbyte/wizbuddy/security/WebSecurity.java
  src/test/java/com/intbyte/wizbuddy/board/service/SubsBoardServiceTests.java
  src/test/java/com/intbyte/wizbuddy/comment/service/CommentServiceTests.java
  src/test/java/com/intbyte/wizbuddy/like/service/ManualBoardLikedServiceTests.java
  src/test/java/com/intbyte/wizbuddy/like/service/NoticeBoardLikedServiceTests.java
Labels: enhancement, fix

#139 ♻️ 코드 수정 : 매뉴얼 게시판, 공지사항 게시판 불필요한 주석 제거
  src/main/java/com/intbyte/wizbuddy/board/controller/ManualBoardController.java
  src/main/java/com/intbyte/wizbuddy/board/controller/NoticeBoardController.java
  src/main/java/com/intbyte/wizbuddy/board/domain/DeleteManualBoardInfo.java
  src/main/java/com/intbyte/wizbuddy/board/domain/DeleteNoticeBoardInfo.java
  src/main/java/com/intbyte/wizbuddy/board/domain/EditManualBoardInfo.java
  src/main/java/com/intbyte/wizbuddy/board/domain/EditNoticeBoardInfo.java
  src/main/java/com/intbyte/wizbuddy/board/dto/ManualBoardDTO.java
  src/main/java/com/intbyte/wizbuddy/board/dto/NoticeBoardDTO.java
  src/main/java/com/intbyte/wizbuddy/board/service/ManualBoardService.java
  src/main/java/com/intbyte/wizbuddy/board/service/NoticeBoardService.java
  src/main/java/com/intbyte/wizbuddy/board/vo/request/RequestInsertManualBoardVO.java
  src/main/java/com/intbyte/wizbuddy/board/vo/request/RequestInsertNoticeBoardVO.java
  src/main/java/com/intbyte/wizbuddy/board/vo/request/RequestUpdateManualBoardVO.java
  src/main/java/com/intbyte/wizbuddy/board/vo/request/RequestUpdateNoticeBoardVO.java
  src/main/java/com/intbyte/wizbuddy/board/vo/response/ResponseFindManualBoardVO.java
  src/main/java/com/intbyte/wizbuddy/board/vo/response/ResponseFindNoticeBoardVO.java
  src/main/java/com/intbyte/wizbuddy/board/vo/response/ResponseInsertManualBoardVO.java
  src/main/java/com/intbyte/wizbuddy/board/vo/response/ResponseInsertNoticeBoardVO.java
  src/main/java/com/intbyte/wizbuddy/board/vo/response/ResponseUpdateManualBoardVO.java
  src/main/java/com/intbyte/wizbuddy/board/vo/response/ResponseUpdateNoticeBoardVO.java
  src/main/java/com/intbyte/wizbuddy/mapper/ManualBoardMapper.java
  src/main/java/com/intbyte/wizbuddy/mapper/NoticeBoardMapper.java
  src/main/java/com/intbyte/wizbuddy/security/WebSecurity.java
  src/main/resources/com/intbyte/wizbuddy/mapper/ManualBoardMapper.xml
  src/main/resources/com/intbyte/wizbuddy/mapper/NoticeBoardMapper.xml
  src/test/java/com/intbyte/wizbuddy/board/service/ManualBoardServiceTests.java
  src/test/java/com/intbyte/wizbuddy/board/service/NoticeBoardServiceTests.java
Labels: enhancement, fix

#140 ♻️ 코드 수정: Task 관련 코드 수정
  src/main/java/com/intbyte/wizbuddy/task/controller/TaskController.java
  src/main/java/com/intbyte/wizbuddy/taskperchecklist/controller/TaskPerCheckListController.java
Labels: fix

#141 ♻️ 코드 수정: shop 관련 코드 수정
  src/main/java/com/intbyte/wizbuddy/employeepershop/controller/EmployeePerShopController.java
  src/main/java/com/intbyte/wizbuddy/employeepershop/service/EmployeePerShopService.java
  src/main/java/com/intbyte/wizbuddy/mapper/ShopMapper.java
  src/main/java/com/intbyte/wizbuddy/shop/service/ShopService.java
  src/main/resources/com/intbyte/wizbuddy/mapper/ShopMapper.xml
Labels: enhancement

#143 ✨ 기능 추가 : Swagger Operation 달기
  src/main/java/com/intbyte/wizbuddy/board/controller/SubsBoardController.java
  src/main/java/com/intbyte/wizbuddy/comment/controller/CommentController.java
  src/main/java/com/intbyte/wizbuddy/like/controller/ManualBoardLikeController.java
  src/main/java/com/intbyte/wizbuddy/like/controller/NoticeBoardLikeController.java
  src/main/java/com/intbyte/wizbuddy/security/WebSecurity.java
Labels: enhancement, fix

#145 ✨ 기능 추가: Swagger Operation 추가
  src/main/java/com/intbyte/wizbuddy/schedule/controller/ScheduleController.java
Labels: enhancement

#146 ✨ 기능 추가: swagger 설정 완료
  src/main/java/com/intbyte/wizbuddy/board/controller/ManualBoardController.java
  src/main/java/com/intbyte/wizbuddy/checklist/controller/CheckListController.java
  src/main/java/com/intbyte/wizbuddy/task/controller/TaskController.java
  src/main/java/com/intbyte/wizbuddy/taskperchecklist/controller/TaskPerCheckListController.java
Labels: enhancement

#147 ♻️ 코드 수정: shop, user 관련 코드 수정
  src/main/java/com/intbyte/wizbuddy/security/WebSecurity.java
  src/main/java/com/intbyte/wizbuddy/shop/controller/ShopController.java
  src/main/java/com/intbyte/wizbuddy/shop/service/ShopService.java
  src/main/java/com/intbyte/wizbuddy/user/controller/UserController.java
  src/main/java/com/intbyte/wizbuddy/user/service/EmployeeService.java
  src/main/java/com/intbyte/wizbuddy/user/service/EmployerService.java
Labels: fix

#160 ♻️✨ 코드 수정 및 기능 추가: 파일 구조 변경
  wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/board/controller/SubsBoardController.java
  wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/board/domain/EditSubsBoardInfo.java
  wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/board/domain/entity/SubsBoard.java
  wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/board/dto/SubsBoardDTO.java
  wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/board/repository/SubsBoardRepository.java
  wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/board/service/SubsBoardService.java
  wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/board/vo/request/RequestDeleteSubsBoardVO.java
  wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/board/vo/request/RequestInsertSubsBoardVO.java
  wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/board/vo/request/RequestModifySubsBoardVO.java
  wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/board/vo/response/ResponseDeleteSubsBoardVO.java
  wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/board/vo/response/ResponseFindSubsBoardVO.java
  wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/board/vo/response/ResponseInsertSubsBoardVO.java
  wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/board/vo/response/ResponseModifySubsBoardVO.java
  wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/comment/controller/CommentController.java
  wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/comment/domain/EditCommentInfo.java
  wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/comment/domain/Entity/Comment.java
  wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/comment/dto/CommentDTO.java
  wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/comment/repository/CommentRepository.java
  wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/comment/service/CommentService.java
  wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/comment/vo/request/RequestAdoptCommentVO.java
  wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/comment/vo/request/RequestDeleteCommentVO.java
  wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/comment/vo/request/RequestInsertCommentVO.java
  wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/comment/vo/request/RequestModifyCommentVO.java
  wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/comment/vo/response/ResponseAdoptCommentVO.java
  wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/comment/vo/response/ResponseDeleteCommentVO.java
  wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/comment/vo/response/ResponseFindCommentVO.java
  wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/comment/vo/response/ResponseInsertCommentVO.java
  wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/comment/vo/response/ResponseModifyCommentVO.java
  wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/exception/board/AlreadyAdoptedSubsBoardException.java
  wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/exception/board/SubsBoardNotFoundException.java
  wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/exception/comment/CommentNotFoundException.java
  wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/exception/schedule/WorkingPartCodeNotEqualsException.java
  wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/mapper/CommentMapper.java
  wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/mapper/EmployeeWorkingPartMapper.java
  wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/mapper/SubsBoardMapper.java
  wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/schedule/controller/ScheduleController.java
  wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/schedule/repository/WeeklyScheduleRepository.java
  wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/schedule/service/ScheduleService.java
  wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/schedule/vo/request/RequestModifyScheduleByCommentVO.java
  wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/schedule/vo/response/ResponseModifyScheduleByCommentVO.java
Labels: fix

#165 command Service 테스트 코드 추가, Aggregate 패키지명 변경, UserServiceImpl 코드 수정, Authentication 을 활용해 검증 구문 추가
  wizbuddy-user-service/src/main/java/com/intbyte/wizbuddy/user/command/application/controller/UserController.java
  wizbuddy-user-service/src/main/java/com/intbyte/wizbuddy/user/command/application/service/EmployeeService.java
  wizbuddy-user-service/src/main/java/com/intbyte/wizbuddy/user/command/application/service/EmployerService.java
  wizbuddy-user-service/src/main/java/com/intbyte/wizbuddy/user/command/application/service/UserService.java
  wizbuddy-user-service/src/main/java/com/intbyte/wizbuddy/user/command/application/service/UserServiceImpl.java
  wizbuddy-user-service/src/main/java/com/intbyte/wizbuddy/user/command/domain/aggregate/Employee.java
  wizbuddy-user-service/src/main/java/com/intbyte/wizbuddy/user/command/domain/aggregate/Employer.java
  wizbuddy-user-service/src/main/java/com/intbyte/wizbuddy/user/command/domain/aggregate/UserEntity.java
  wizbuddy-user-service/src/main/java/com/intbyte/wizbuddy/user/command/domain/aggregate/vo/request/RequestInsertEmployeeVO.java
  wizbuddy-user-service/src/main/java/com/intbyte/wizbuddy/user/command/domain/aggregate/vo/request/RequestInsertEmployerVO.java
  wizbuddy-user-service/src/main/java/com/intbyte/wizbuddy/user/command/domain/aggregate/vo/request/RequestLoginVO.java
  wizbuddy-user-service/src/main/java/com/intbyte/wizbuddy/user/command/domain/aggregate/vo/request/RequestRegisterEmployeeVO.java
  wizbuddy-user-service/src/main/java/com/intbyte/wizbuddy/user/command/domain/aggregate/vo/request/RequestRegisterEmployerVO.java
  wizbuddy-user-service/src/main/java/com/intbyte/wizbuddy/user/command/domain/aggregate/vo/request/RequestSignInUserVO.java
  wizbuddy-user-service/src/main/java/com/intbyte/wizbuddy/user/command/domain/aggregate/vo/response/ResponseInsertEmployeeVO.java
  wizbuddy-user-service/src/main/java/com/intbyte/wizbuddy/user/command/domain/aggregate/vo/response/ResponseInsertEmployerVO.java
  wizbuddy-user-service/src/main/java/com/intbyte/wizbuddy/user/command/domain/entity/vo/response/ResponseInsertEmployeeVO.java
  wizbuddy-user-service/src/main/java/com/intbyte/wizbuddy/user/command/domain/entity/vo/response/ResponseInsertEmployerVO.java
  wizbuddy-user-service/src/main/java/com/intbyte/wizbuddy/user/command/domain/repository/EmployeeRepository.java
  wizbuddy-user-service/src/main/java/com/intbyte/wizbuddy/user/command/domain/repository/EmployerRepository.java
  wizbuddy-user-service/src/main/java/com/intbyte/wizbuddy/user/command/domain/repository/UserRepository.java
  wizbuddy-user-service/src/main/java/com/intbyte/wizbuddy/user/query/config/MybatisConfiguration.java
  wizbuddy-user-service/src/main/java/com/intbyte/wizbuddy/user/query/repository/EmployeeMapper.java
  wizbuddy-user-service/src/main/java/com/intbyte/wizbuddy/user/query/repository/EmployerMapper.java
  wizbuddy-user-service/src/main/java/com/intbyte/wizbuddy/user/query/service/EmployeeService.java
  wizbuddy-user-service/src/main/java/com/intbyte/wizbuddy/user/query/service/EmployerService.java
  wizbuddy-user-service/src/main/java/com/intbyte/wizbuddy/user/security/AuthenticationFilter.java
  wizbuddy-user-service/src/main/resources/com/intbyte/wizbuddy/user/query/repository/EmployeeMapper.xml
  wizbuddy-user-service/src/main/resources/com/intbyte/wizbuddy/user/query/repository/EmployerMapper.xml
  wizbuddy-user-service/src/main/resources/com/intbyte/wizbuddy/user/query/repository/UserAndEmployeeMapper.xml
  wizbuddy-user-service/src/main/resources/com/intbyte/wizbuddy/user/query/repository/UserAndEmployerMapper.xml
  wizbuddy-user-service/src/test/java/com/intbyte/wizbuddy/user/command/application/service/EmployeeServiceTests.java
  wizbuddy-user-service/src/test/java/com/intbyte/wizbuddy/user/command/application/service/EmployerServiceTests.java
  wizbuddy-user-service/src/test/java/com/intbyte/wizbuddy/user/command/application/service/UserServiceImplTests.java
Labels: enhancement, fix

#166 ♻️ 코드 수정: AntPathRequestMatcher 권한 수정
  wizbuddy-user-service/src/main/java/com/intbyte/wizbuddy/user/security/WebSecurity.java
Labels: fix

#167 ♻️✨ 코드 수정 및 기능 추가: EmployeeWorkingPartService 코드 리팩토링 및 예외처리 수정
  wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/employeeworkingpart/command/application/service/EmployeeWorkingPartServiceImpl.java
  wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/employeeworkingpart/command/domain/repository/EmployeeWorkingPartRepository.java
  wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/employeeworkingpart/common/exception/EmployeeCodeNotFoundException.java
  wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/employeeworkingpart/common/exception/ScheduleNotFoundException.java
  wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/employeeworkingpart/common/exception/StatusEnum.java
  wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/employeeworkingpart/common/exception/WorkingDateAndTimeEqualsException.java
  wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/employeeworkingpart/query/config/MybatisConfiguration.java
  wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/employeeworkingpart/query/repository/EmployeeWorkingPartMapper.java
  wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/employeeworkingpart/query/service/EmployeeWorkingPartServiceImpl.java
  wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/weeklyschedule/command/application/service/WeeklyScheduleServiceImpl.java
  wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/weeklyschedule/command/domain/repository/WeeklyScheduleRepository.java
  wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/weeklyschedule/query/config/MybatisConfiguration.java
  wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/weeklyschedule/query/service/WeeklyScheduleServiceImpl.java
  wizbuddy-schedule-service/src/main/resources/com/intbyte/wizbuddy/employeeworkingpart/query/repository/EmployeeWorkingPartMapper.xml
  wizbuddy-schedule-service/src/main/resources/com/intbyte/wizbuddy/weeklyschedule/query/repository/WeeklyScheduleMapper.xml
  wizbuddy-schedule-service/src/test/java/com/intbyte/wizbuddy/employeeworkingpart/query/service/EmployeeWorkingPartServiceImplTests.java
  wizbuddy-schedule-service/src/test/java/com/intbyte/wizbuddy/weeklyschedule/command/application/service/WeeklyScheduleServiceImplTest.java
  wizbuddy-schedule-service/src/test/java/com/intbyte/wizbuddy/weeklyschedule/query/service/WeeklyScheduleServiceImplTest.java
Labels: fix

#168 ✨ 기능 수정: 댓글 채택 및 스케줄 코드 수정 기능 테스트 수정
  wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/comment/infrastructure/repository/SubsBoardRepository.java
  wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/comment/infrastructure/service/InfraAdoptServiceImpl.java
  wizbuddy-schedule-service/src/test/java/com/intbyte/wizbuddy/comment/infrastructure/service/InfraAdoptServiceImplTests.java
Labels: enhancement, fix

#169 ♻️✨ 코드 수정 및 기능 추가: 댓글 채택해서 스케줄 수정 기능 예외처리 수정
  wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/comment/infrastructure/repository/EmployeeWorkingPartRepository.java
  wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/comment/infrastructure/service/InfraAdoptServiceImpl.java
Labels: fix

#172 ♻️ 코드 수정 : taskService Bean name 설정 및 코드 수정
  wizbuddy-task-service/src/main/java/com/intbyte/wizbuddy/checklist/command/application/controller/CheckListController.java
  wizbuddy-task-service/src/main/java/com/intbyte/wizbuddy/checklist/query/controller/CheckListController.java
  wizbuddy-task-service/src/main/java/com/intbyte/wizbuddy/task/command/application/controller/TaskController.java
  wizbuddy-task-service/src/main/java/com/intbyte/wizbuddy/task/command/infrastructure/client/ShopServiceClient.java
  wizbuddy-task-service/src/main/java/com/intbyte/wizbuddy/task/query/controller/TaskController.java
  wizbuddy-task-service/src/main/java/com/intbyte/wizbuddy/taskperchecklist/command/application/controller/TaskPerCheckListController.java
  wizbuddy-task-service/src/main/java/com/intbyte/wizbuddy/taskperchecklist/query/config/MybatisConfiguration.java
  wizbuddy-task-service/src/main/java/com/intbyte/wizbuddy/taskperchecklist/query/controller/TaskPerCheckListController.java
  wizbuddy-task-service/src/main/resources/com/intbyte/wizbuddy/taskperchecklist/query/repository/TaskPerCheckListMapper.xml
Labels: fix

#173 ♻️✨ 코드 수정 및 기능 추가: 코드 리팩토링
  wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/employeeworkingpart/command/application/controller/EmployeeWorkingPartController.java
  wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/employeeworkingpart/command/application/service/EmployeeWorkingPartService.java
  wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/employeeworkingpart/command/application/service/EmployeeWorkingPartServiceImpl.java
  wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/employeeworkingpart/command/domain/aggregate/vo/response/ResponseRegistEmployeeVO.java
  wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/weeklyschedule/command/application/controller/WeeklyScheduleController.java
  wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/weeklyschedule/command/application/service/WeeklyScheduleService.java
  wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/weeklyschedule/command/application/service/WeeklyScheduleServiceImpl.java
  wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/weeklyschedule/command/domain/aggregate/vo/response/ResponseRegistWeeklyScheduleVO.java
  wizbuddy-schedule-service/src/test/java/com/intbyte/wizbuddy/employeeworkingpart/command/application/service/EmployeeWorkingPartServiceImplTests.java
  wizbuddy-schedule-service/src/test/java/com/intbyte/wizbuddy/weeklyschedule/command/application/service/WeeklyScheduleServiceImplTest.java
Labels: fix

#174 ♻️ 코드 수정: 예외 처리 중복 삭제
  wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/board/command/application/service/SubsBoardServiceImpl.java
  wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/board/common/StatusEnum.java
  wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/board/common/exception/SubsBoardNotFoundException.java
  wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/board/query/application/service/SubsBoardServiceImpl.java
  wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/comment/command/application/service/CommentServiceImpl.java
  wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/comment/common/StatusEnum.java
  wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/comment/common/exception/CommentNotFoundException.java
  wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/comment/query/application/service/CommentServiceImpl.java
  wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/common/exception/CommonException.java
  wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/common/exception/ExceptionDTO.java
  wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/common/exception/GlobalExceptionHandler.java
  wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/common/exception/ResponseDTO.java
  wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/common/exception/StatusEnum.java
  wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/employeeworkingpart/command/application/service/EmployeeWorkingPartServiceImpl.java
  wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/employeeworkingpart/command/domain/aggregate/entity/EmployeeWorkingPart.java
  wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/employeeworkingpart/command/domain/repository/EmployeeWorkingPartRepository.java
  wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/employeeworkingpart/common/exception/EmployeeCodeNotFoundException.java
  wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/employeeworkingpart/common/exception/ScheduleNotFoundException.java
  wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/employeeworkingpart/common/exception/StatusEnum.java
  wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/employeeworkingpart/common/exception/WorkingDateAndTimeEqualsException.java
  wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/employeeworkingpart/query/service/EmployeeWorkingPartServiceImpl.java
  wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/weeklyschedule/command/application/service/WeeklyScheduleServiceImpl.java
  wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/weeklyschedule/common/exception/ScheduleCodeDuplicateException.java
  wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/weeklyschedule/common/exception/StatusEnum.java
Labels: fix

#175 ✨ 기능 추가: ScheduleInfraService 추가
  wizbuddy-schedule-service/build.gradle
  wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/WizbuddyScheduleServiceApplication.java
  wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/config/FeignClientConfig.java
  wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/employeeworkingpart/command/application/service/EmployeeWorkingPartServiceImpl.java
  wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/employeeworkingpart/command/infrastructure/client/UserServiceClient.java
  wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/employeeworkingpart/command/infrastructure/dto/EmployeeDTO.java
  wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/employeeworkingpart/command/infrastructure/dto/WeeklyScheduleDTO.java
  wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/employeeworkingpart/command/infrastructure/service/ScheduleInfraService.java
  wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/employeeworkingpart/command/infrastructure/service/ScheduleInfraServiceImpl.java
  wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/employeeworkingpart/query/service/EmployeeWorkingPartServiceImpl.java
  wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/weeklyschedule/command/application/service/WeeklyScheduleServiceImpl.java
  wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/weeklyschedule/query/repository/WeeklyScheduleMapper.java
  wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/weeklyschedule/query/service/WeeklyScheduleService.java
  wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/weeklyschedule/query/service/WeeklyScheduleServiceImpl.java
  wizbuddy-schedule-service/src/main/resources/com/intbyte/wizbuddy/weeklyschedule/query/repository/WeeklyScheduleMapper.xml
Labels: enhancement

#176 매뉴얼, 공지사항 게시판 좋아요 패키지 수정 및 리팩토링, 좋아요 조회 기능 추가
  wizbuddy-shop-service/src/main/java/com/intbyte/wizbuddy/like/command/application/controller/ManualBoardLikeController.java
  wizbuddy-shop-service/src/main/java/com/intbyte/wizbuddy/like/command/application/controller/NoticeBoardLikeController.java
  wizbuddy-shop-service/src/main/java/com/intbyte/wizbuddy/like/command/application/service/ManualBoardLikedService.java
  wizbuddy-shop-service/src/main/java/com/intbyte/wizbuddy/like/command/application/service/NoticeBoardLikedService.java
  wizbuddy-shop-service/src/main/java/com/intbyte/wizbuddy/like/command/domain/entity/ManualBoardLiked.java
  wizbuddy-shop-service/src/main/java/com/intbyte/wizbuddy/like/command/domain/entity/vo/request/RequestInsertManualBoardLikeVO.java
  wizbuddy-shop-service/src/main/java/com/intbyte/wizbuddy/like/command/domain/entity/vo/request/RequestInsertNoticeBoardLikeVO.java
  wizbuddy-shop-service/src/main/java/com/intbyte/wizbuddy/like/command/domain/entity/vo/response/ResponseInsertManualBoardLikeVO.java
  wizbuddy-shop-service/src/main/java/com/intbyte/wizbuddy/like/command/domain/entity/vo/response/ResponseInsertNoticeBoardLikeVO.java
  wizbuddy-shop-service/src/main/java/com/intbyte/wizbuddy/like/command/infrastructure/service/ManualBoardLikedInfraStructureService.java
  wizbuddy-shop-service/src/main/java/com/intbyte/wizbuddy/like/command/infrastructure/service/ManualBoardLikedInfraStructureServiceImpl.java
  wizbuddy-shop-service/src/main/java/com/intbyte/wizbuddy/like/command/infrastructure/service/NoticeBoardLikedInfraStructureService.java
  wizbuddy-shop-service/src/main/java/com/intbyte/wizbuddy/like/command/infrastructure/service/NoticeBoardLikedInfraStructureServiceImpl.java
  wizbuddy-shop-service/src/main/java/com/intbyte/wizbuddy/like/query/controller/ManualBoardLikeController.java
  wizbuddy-shop-service/src/main/java/com/intbyte/wizbuddy/like/query/controller/NoticeBoardLikeController.java
  wizbuddy-shop-service/src/main/java/com/intbyte/wizbuddy/like/query/dto/ManualBoardLikedDTO.java
  wizbuddy-shop-service/src/main/java/com/intbyte/wizbuddy/like/query/dto/NoticeBoardLikedDTO.java
  wizbuddy-shop-service/src/main/java/com/intbyte/wizbuddy/like/query/repository/ManualBoardLikedMapper.java
  wizbuddy-shop-service/src/main/java/com/intbyte/wizbuddy/like/query/repository/NoticeBoardLikedMapper.java
  wizbuddy-shop-service/src/main/java/com/intbyte/wizbuddy/like/query/service/ManualBoardLikedService.java
  wizbuddy-shop-service/src/main/java/com/intbyte/wizbuddy/like/query/service/NoticeBoardLikedService.java
  wizbuddy-shop-service/src/main/resources/com/intbyte/wizbuddy/like/query/repository/ManualBoardLikedMapper.xml
  wizbuddy-shop-service/src/main/resources/com/intbyte/wizbuddy/like/query/repository/NoticeBoardLikedMapper.xml
Labels: enhancement, fix

#178 ✨ 기능 추가 / 수정: task-service의 테스트코드 작성, 통과
  wizbuddy-task-service/src/main/java/com/intbyte/wizbuddy/checklist/command/application/service/AppCheckListServiceImpl.java
  wizbuddy-task-service/src/main/java/com/intbyte/wizbuddy/checklist/command/domain/aggregate/vo/RequestInsertTaskToCheckListVO.java
  wizbuddy-task-service/src/main/java/com/intbyte/wizbuddy/checklist/command/domain/service/DomainCheckListServiceImpl.java
  wizbuddy-task-service/src/main/java/com/intbyte/wizbuddy/checklist/command/infrastructure/service/InfraCheckListService.java
  wizbuddy-task-service/src/main/java/com/intbyte/wizbuddy/checklist/command/infrastructure/service/InfraCheckListServiceImpl.java
  wizbuddy-task-service/src/main/java/com/intbyte/wizbuddy/checklist/query/service/CheckListServiceImpl.java
  wizbuddy-task-service/src/main/java/com/intbyte/wizbuddy/task/command/application/service/AppTaskService.java
  wizbuddy-task-service/src/main/java/com/intbyte/wizbuddy/task/command/application/service/AppTaskServiceImpl.java
  wizbuddy-task-service/src/main/java/com/intbyte/wizbuddy/task/query/controller/TaskController.java
  wizbuddy-task-service/src/main/java/com/intbyte/wizbuddy/task/query/dto/TaskQueryDTO.java
  wizbuddy-task-service/src/main/java/com/intbyte/wizbuddy/task/query/repository/TaskMapper.java
  wizbuddy-task-service/src/main/java/com/intbyte/wizbuddy/task/query/service/TaskService.java
  wizbuddy-task-service/src/main/java/com/intbyte/wizbuddy/task/query/service/TaskServiceImpl.java
  wizbuddy-task-service/src/main/java/com/intbyte/wizbuddy/taskperchecklist/command/application/service/AppTaskPerCheckListServiceImpl.java
  wizbuddy-task-service/src/main/java/com/intbyte/wizbuddy/taskperchecklist/query/controller/TaskPerCheckListController.java
  wizbuddy-task-service/src/main/java/com/intbyte/wizbuddy/taskperchecklist/query/dto/TaskPerCheckListQueryDTO.java
  wizbuddy-task-service/src/main/java/com/intbyte/wizbuddy/taskperchecklist/query/repository/TaskPerCheckListMapper.java
  wizbuddy-task-service/src/main/java/com/intbyte/wizbuddy/taskperchecklist/query/service/TaskPerCheckListService.java
  wizbuddy-task-service/src/main/java/com/intbyte/wizbuddy/taskperchecklist/query/service/TaskPerCheckListServiceImpl.java
  wizbuddy-task-service/src/main/resources/com/intbyte/wizbuddy/task/query/repository/TaskMapper.xml
  wizbuddy-task-service/src/main/resources/com/intbyte/wizbuddy/taskperchecklist/query/repository/TaskPerCheckListMapper.xml
  wizbuddy-task-service/src/test/java/com/intbyte/wizbuddy/checklist/command/application/service/CheckListServiceTests.java
  wizbuddy-task-service/src/test/java/com/intbyte/wizbuddy/checklist/query/service/CheckListServiceTests.java
  wizbuddy-task-service/src/test/java/com/intbyte/wizbuddy/task/command/application/service/TaskServiceTests.java
  wizbuddy-task-service/src/test/java/com/intbyte/wizbuddy/task/query/service/TaskServiceTests.java
  wizbuddy-task-service/src/test/java/com/intbyte/wizbuddy/taskperchecklist/command/application/service/TaskPerCheckListTests.java
  wizbuddy-task-service/src/test/java/com/intbyte/wizbuddy/taskperchecklist/query/service/TaskPerCheckListTests.java
Labels: bug, enhancement, fix

#179 ✨ 기능 추가: 게시글 삭제시 관련 자동 댓글 삭제 관련 기능 완료
  wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/board/command/application/controller/SubsBoardController.java
  wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/board/command/application/service/SubsBoardService.java
  wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/board/command/application/service/SubsBoardServiceImpl.java
  wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/board/command/domain/aggregate/SubsBoard.java
  wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/board/command/domain/aggregate/vo/EditSubsBoardVO.java
  wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/board/command/domain/repository/SubsBoardRepository.java
  wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/board/infrastructure/event/SubsBoardDeletedEvent.java
  wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/board/infrastructure/event/SubsBoardEventListener.java
  wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/board/infrastructure/service/InfraSubsBoardService.java
  wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/board/infrastructure/service/InfraSubsBoardServiceImpl.java
  wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/board/query/application/service/SubsBoardServiceImpl.java
  wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/board/query/domain/aggregate/SubsBoard.java
  wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/comment/command/application/controller/CommentController.java
  wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/comment/command/application/service/CommentService.java
  wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/comment/command/application/service/CommentServiceImpl.java
  wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/comment/command/domain/aggregate/Comment.java
  wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/comment/command/domain/aggregate/vo/EditCommentVO.java
  wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/comment/command/domain/repository/CommentRepository.java
  wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/comment/infrastructure/exception/AlreadyAdoptedSubsBoardException.java
  wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/comment/infrastructure/exception/ScheduleNotFoundException.java
  wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/comment/infrastructure/exception/StatusEnum.java
  wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/comment/infrastructure/exception/SubsBoardNotFoundException.java
  wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/comment/infrastructure/exception/WorkingDateAndTimeEqualsException.java
  wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/comment/infrastructure/exception/WorkingPartCodeNotEqualsException.java
  wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/comment/infrastructure/repository/CommentRepository.java
  wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/comment/infrastructure/repository/EmployeeWorkingPartRepository.java
  wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/comment/infrastructure/repository/SubsBoardRepository.java
  wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/comment/infrastructure/service/InfraAdoptServiceImpl.java
  wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/comment/query/application/service/CommentServiceImpl.java
  wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/common/exception/StatusEnum.java
  wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/employeeworkingpart/command/application/service/EmployeeWorkingPartService.java
  wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/employeeworkingpart/command/application/service/EmployeeWorkingPartServiceImpl.java
  wizbuddy-schedule-service/src/test/java/com/intbyte/wizbuddy/board/command/application/service/SubsBoardServiceImplTests.java
  wizbuddy-schedule-service/src/test/java/com/intbyte/wizbuddy/board/infrastructure/service/InfraSubsBoardServiceImplTests.java
  wizbuddy-schedule-service/src/test/java/com/intbyte/wizbuddy/comment/command/application/service/CommentServiceImplTests.java
  wizbuddy-schedule-service/src/test/java/com/intbyte/wizbuddy/comment/infrastructure/service/InfraAdoptServiceImplTests.java
Labels: bug, enhancement, fix

#180 ✨ 기능 추가/수정: 매뉴얼 게시판, 공지사항 게시판 관련 테스트코드 추가 및 수정
  wizbuddy-shop-service/src/main/java/com/intbyte/wizbuddy/board/command/application/dto/RequestEditManualBoardDTO.java
  wizbuddy-shop-service/src/main/java/com/intbyte/wizbuddy/board/command/application/dto/RequestEditNoticeBoardDTO.java
  wizbuddy-shop-service/src/main/java/com/intbyte/wizbuddy/board/command/domain/entity/vo/response/ResponseUpdateManualBoardVO.java
  wizbuddy-shop-service/src/main/java/com/intbyte/wizbuddy/board/query/dto/ManualBoardDTO.java
  wizbuddy-shop-service/src/main/java/com/intbyte/wizbuddy/like/command/application/controller/ManualBoardLikeController.java
  wizbuddy-shop-service/src/main/java/com/intbyte/wizbuddy/like/command/application/service/ManualBoardLikedService.java
  wizbuddy-shop-service/src/main/java/com/intbyte/wizbuddy/like/command/application/service/NoticeBoardLikedService.java
  wizbuddy-shop-service/src/main/java/com/intbyte/wizbuddy/like/command/domain/repository/ManualBoardLikedRepository.java
  wizbuddy-shop-service/src/main/java/com/intbyte/wizbuddy/like/command/domain/repository/NoticeBoardLikedRepository.java
  wizbuddy-shop-service/src/main/java/com/intbyte/wizbuddy/like/query/controller/ManualBoardLikeController.java
  wizbuddy-shop-service/src/main/java/com/intbyte/wizbuddy/like/query/controller/NoticeBoardLikeController.java
  wizbuddy-shop-service/src/main/resources/com/intbyte/wizbuddy/like/query/repository/ManualBoardLikedMapper.xml
  wizbuddy-shop-service/src/test/java/com/intbyte/wizbuddy/board/command/application/service/ManualBoardServiceTests.java
  wizbuddy-shop-service/src/test/java/com/intbyte/wizbuddy/board/command/application/service/NoticeBoardServiceTests.java
  wizbuddy-shop-service/src/test/java/com/intbyte/wizbuddy/board/query/service/ManualBoardServiceTests.java
  wizbuddy-shop-service/src/test/java/com/intbyte/wizbuddy/board/query/service/NoticeBoardServiceTests.java
  wizbuddy-shop-service/src/test/java/com/intbyte/wizbuddy/like/command/application/service/ManualBoardServiceLikeTests.java
  wizbuddy-shop-service/src/test/java/com/intbyte/wizbuddy/like/command/application/service/NoticeBoardServiceLikeTests.java
  wizbuddy-shop-service/src/test/java/com/intbyte/wizbuddy/like/query/service/ManualBoardServiceLikeTests.java
  wizbuddy-shop-service/src/test/java/com/intbyte/wizbuddy/like/query/service/NoticeBoardServiceLikeTests.java
Labels: enhancement, fix

#181 ♻️ 코드 수정: 매뉴얼 게시판, 공지사항 게시판 좋아요 조회 테스트코드 수정
  wizbuddy-shop-service/src/test/java/com/intbyte/wizbuddy/like/query/service/ManualBoardServiceLikeTests.java
  wizbuddy-shop-service/src/test/java/com/intbyte/wizbuddy/like/query/service/NoticeBoardServiceLikeTests.java
Labels: fix

#182 코드 수정: DTO에 생성자 어노테이션 재추가 및 basePackage 경로 수정 및 서비스 코드 수정
  wizbuddy-user-service/src/main/java/com/intbyte/wizbuddy/user/command/application/dto/RequestEditEmployeeDTO.java
  wizbuddy-user-service/src/main/java/com/intbyte/wizbuddy/user/command/application/dto/RequestEditEmployerDTO.java
  wizbuddy-user-service/src/main/java/com/intbyte/wizbuddy/user/command/application/service/EmployeeService.java
  wizbuddy-user-service/src/main/java/com/intbyte/wizbuddy/user/command/application/service/EmployerService.java
  wizbuddy-user-service/src/main/java/com/intbyte/wizbuddy/user/common/exception/GlobalExceptionHandler.java
  wizbuddy-user-service/src/main/java/com/intbyte/wizbuddy/user/query/dto/EmployeeDTO.java
  wizbuddy-user-service/src/main/java/com/intbyte/wizbuddy/user/query/dto/EmployerDTO.java
  wizbuddy-user-service/src/main/java/com/intbyte/wizbuddy/user/query/dto/UserDTO.java
  wizbuddy-user-service/src/main/java/com/intbyte/wizbuddy/user/query/repository/EmployeeMapper.java
  wizbuddy-user-service/src/main/java/com/intbyte/wizbuddy/user/query/repository/EmployerMapper.java
  wizbuddy-user-service/src/main/resources/com/intbyte/wizbuddy/user/query/repository/EmployeeMapper.xml
  wizbuddy-user-service/src/main/resources/com/intbyte/wizbuddy/user/query/repository/EmployerMapper.xml
Labels: fix

#184 ✨ 기능 추가: 이메일 인증을 위한 Redis 설정 적용 및 추가
  wizbuddy-user-service/build.gradle
  wizbuddy-user-service/src/main/java/com/intbyte/wizbuddy/user/command/application/controller/UserController.java
  wizbuddy-user-service/src/main/java/com/intbyte/wizbuddy/user/command/application/service/EmailVerificationService.java
  wizbuddy-user-service/src/main/java/com/intbyte/wizbuddy/user/command/application/service/UserServiceImpl.java
  wizbuddy-user-service/src/main/java/com/intbyte/wizbuddy/user/command/domain/aggregate/vo/EmailVerificationVO.java
  wizbuddy-user-service/src/main/java/com/intbyte/wizbuddy/user/command/domain/aggregate/vo/ResponseEmailMessageVO.java
  wizbuddy-user-service/src/main/java/com/intbyte/wizbuddy/user/common/exception/StatusEnum.java
  wizbuddy-user-service/src/main/java/com/intbyte/wizbuddy/user/config/EmailConfig.java
  wizbuddy-user-service/src/main/java/com/intbyte/wizbuddy/user/config/RedisConfig.java
Labels: enhancement

#189 ♻️ 코드 수정: 좋아요 조회 시 좋아요 누른 회원 정보 조회하도록 수정
  wizbuddy-shop-service/src/main/java/com/intbyte/wizbuddy/infrastructure/UserTypeEnum.java
  wizbuddy-shop-service/src/main/java/com/intbyte/wizbuddy/infrastructure/client/UserServiceClient.java
  wizbuddy-shop-service/src/main/java/com/intbyte/wizbuddy/infrastructure/dto/UserDTO.java
  wizbuddy-shop-service/src/main/java/com/intbyte/wizbuddy/like/query/controller/ManualBoardLikeController.java
  wizbuddy-shop-service/src/main/java/com/intbyte/wizbuddy/like/query/controller/NoticeBoardLikeController.java
  wizbuddy-shop-service/src/main/java/com/intbyte/wizbuddy/like/query/service/ManualBoardLikedService.java
  wizbuddy-shop-service/src/main/java/com/intbyte/wizbuddy/like/query/service/NoticeBoardLikedService.java
  wizbuddy-shop-service/src/test/java/com/intbyte/wizbuddy/like/query/service/ManualBoardServiceLikeTests.java
  wizbuddy-shop-service/src/test/java/com/intbyte/wizbuddy/like/query/service/NoticeBoardServiceLikeTests.java
Labels: fix

#190 ♻️ 코드 수정: checklist-service api 수정
  wizbuddy-task-service/src/main/java/com/intbyte/wizbuddy/checklist/command/application/controller/CheckListController.java
  wizbuddy-task-service/src/main/java/com/intbyte/wizbuddy/checklist/query/controller/CheckListController.java
  wizbuddy-task-service/src/main/java/com/intbyte/wizbuddy/task/command/application/controller/TaskController.java
  wizbuddy-task-service/src/main/java/com/intbyte/wizbuddy/task/query/controller/TaskController.java
  wizbuddy-task-service/src/main/java/com/intbyte/wizbuddy/taskperchecklist/command/application/controller/TaskPerCheckListController.java
  wizbuddy-task-service/src/main/java/com/intbyte/wizbuddy/taskperchecklist/query/controller/TaskPerCheckListController.java
  wizbuddy-user-service/src/main/java/com/intbyte/wizbuddy/user/security/WebSecurity.java
Labels: fix

#191 ✨ 기능 수정: api test 하면서 추가적으로 수정해야 할 부분 수정
  wizbuddy-user-service/src/main/java/com/intbyte/wizbuddy/user/command/application/controller/UserController.java
  wizbuddy-user-service/src/main/java/com/intbyte/wizbuddy/user/command/application/service/UserService.java
  wizbuddy-user-service/src/main/java/com/intbyte/wizbuddy/user/command/application/service/UserServiceImpl.java
  wizbuddy-user-service/src/main/java/com/intbyte/wizbuddy/user/command/domain/aggregate/EmployeeAdditional.java
  wizbuddy-user-service/src/main/java/com/intbyte/wizbuddy/user/command/domain/aggregate/UserTypeEnum.java
  wizbuddy-user-service/src/main/java/com/intbyte/wizbuddy/user/query/repository/EmployeeMapper.java
  wizbuddy-user-service/src/main/java/com/intbyte/wizbuddy/user/query/repository/EmployerMapper.java
  wizbuddy-user-service/src/main/java/com/intbyte/wizbuddy/user/query/repository/UserMapper.java
  wizbuddy-user-service/src/main/java/com/intbyte/wizbuddy/user/query/service/EmployeeService.java
  wizbuddy-user-service/src/main/java/com/intbyte/wizbuddy/user/query/service/EmployerService.java
  wizbuddy-user-service/src/main/resources/com/intbyte/wizbuddy/user/query/repository/EmployeeMapper.xml
  wizbuddy-user-service/src/main/resources/com/intbyte/wizbuddy/user/query/repository/EmployerMapper.xml
  wizbuddy-user-service/src/main/resources/com/intbyte/wizbuddy/user/query/repository/UserMapper.xml
  wizbuddy-user-service/src/test/java/com/intbyte/wizbuddy/user/command/application/service/EmployeeServiceTests.java
  wizbuddy-user-service/src/test/java/com/intbyte/wizbuddy/user/command/application/service/EmployerServiceTests.java
Labels: enhancement, fix

#192 ♻️ 코드 수정 : shopservice msa 적용
  wizbuddy-eureka-gateway/src/main/java/com/intbyte/eurekacloudgateway/filter/AuthorizationHeaderFilter.java
  wizbuddy-shop-service/src/main/java/com/intbyte/wizbuddy/config/MybatisConfiguration.java
  wizbuddy-shop-service/src/main/java/com/intbyte/wizbuddy/employeepershop/query/config/MybatisConfiguration.java
  wizbuddy-shop-service/src/main/java/com/intbyte/wizbuddy/like/query/controller/NoticeBoardLikeController.java
  wizbuddy-shop-service/src/main/java/com/intbyte/wizbuddy/security/JwtFilter.java
  wizbuddy-shop-service/src/main/java/com/intbyte/wizbuddy/security/JwtUtil.java
  wizbuddy-shop-service/src/main/java/com/intbyte/wizbuddy/security/WebSecurity.java
  wizbuddy-shop-service/src/main/java/com/intbyte/wizbuddy/shop/command/application/controller/ShopController.java
  wizbuddy-shop-service/src/main/java/com/intbyte/wizbuddy/shop/query/config/MybatisConfiguration.java
  wizbuddy-shop-service/src/main/java/com/intbyte/wizbuddy/shop/query/controller/ShopController.java
  wizbuddy-shop-service/src/main/java/com/intbyte/wizbuddy/shop/query/dto/ShopDTO.java
  wizbuddy-user-service/src/main/java/com/intbyte/wizbuddy/user/command/application/service/UserServiceImpl.java
  wizbuddy-user-service/src/main/java/com/intbyte/wizbuddy/user/security/AuthenticationFilter.java
  wizbuddy-user-service/src/main/java/com/intbyte/wizbuddy/user/security/JwtUtil.java
  wizbuddy-user-service/src/main/java/com/intbyte/wizbuddy/user/security/WebSecurity.java
Labels: enhancement

#193 ✨ 기능 수정: permitAll이 아닌 특정 권한이 필요한 코드 또한 가능하게 수정
  wizbuddy-shop-service/src/main/java/com/intbyte/wizbuddy/security/WebSecurity.java
  wizbuddy-user-service/src/main/java/com/intbyte/wizbuddy/user/command/application/service/UserServiceImpl.java
  wizbuddy-user-service/src/main/java/com/intbyte/wizbuddy/user/security/JwtUtil.java
Labels: fix

#194 ♻ 코드 수정: ScheduleService 수정
  wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/employeeworkingpart/command/application/controller/EmployeeWorkingPartController.java
  wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/employeeworkingpart/command/application/service/EmployeeWorkingPartService.java
  wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/employeeworkingpart/command/application/service/EmployeeWorkingPartServiceImpl.java
  wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/employeeworkingpart/command/domain/aggregate/entity/EmployeeWorkingPart.java
  wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/employeeworkingpart/command/domain/aggregate/repository/EmployeeWorkingPartRepository.java
  wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/employeeworkingpart/command/domain/aggregate/vo/response/ResponseModifyScheduleVO.java
  wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/infrastructure/UserTypeEnum.java
  wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/infrastructure/client/UserServiceClient.java
  wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/infrastructure/dto/EmployeeAdditionalDTO.java
  wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/infrastructure/dto/EmployeeDTO.java
  wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/infrastructure/dto/UserDTO.java
  wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/security/JwtFilter.java
  wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/security/JwtUtil.java
  wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/security/WebSecurity.java
  wizbuddy-schedule-service/src/test/java/com/intbyte/wizbuddy/board/command/application/service/SubsBoardServiceImplTests.java
  wizbuddy-schedule-service/src/test/java/com/intbyte/wizbuddy/board/infrastructure/service/InfraSubsBoardServiceImplTests.java
  wizbuddy-schedule-service/src/test/java/com/intbyte/wizbuddy/board/query/application/service/SubsBoardServiceImplTests.java
  wizbuddy-schedule-service/src/test/java/com/intbyte/wizbuddy/employeeworkingpart/command/application/service/EmployeeWorkingPartServiceImplTests.java
  wizbuddy-schedule-service/src/test/java/com/intbyte/wizbuddy/weeklyschedule/command/application/service/WeeklyScheduleServiceImplTest.java
  wizbuddy-user-service/src/main/java/com/intbyte/wizbuddy/user/query/service/EmployeeService.java
Labels: fix

#195 ✨ 기능 수정: 불필요한 코드 수정 및 api test 하면서 수정이 필요한 기능들 수정
  wizbuddy-shop-service/src/main/java/com/intbyte/wizbuddy/infrastructure/client/UserServiceClient.java
  wizbuddy-shop-service/src/main/java/com/intbyte/wizbuddy/security/WebSecurity.java
  wizbuddy-shop-service/src/main/java/com/intbyte/wizbuddy/shop/command/application/dto/RequestDeleteShopDTO.java
  wizbuddy-shop-service/src/main/java/com/intbyte/wizbuddy/shop/command/application/dto/RequestEditShopDTO.java
  wizbuddy-shop-service/src/main/java/com/intbyte/wizbuddy/shop/command/application/dto/RequestRegisterShopDTO.java
  wizbuddy-shop-service/src/main/java/com/intbyte/wizbuddy/shop/command/application/service/ShopService.java
  wizbuddy-shop-service/src/main/java/com/intbyte/wizbuddy/shop/command/domain/entity/Shop.java
  wizbuddy-shop-service/src/main/java/com/intbyte/wizbuddy/shop/command/domain/entity/vo/request/RequestDeleteShopVO.java
  wizbuddy-shop-service/src/main/java/com/intbyte/wizbuddy/shop/command/domain/entity/vo/request/RequestEditShopVO.java
  wizbuddy-shop-service/src/main/java/com/intbyte/wizbuddy/shop/command/domain/entity/vo/request/RequestRegisterShopVO.java
  wizbuddy-shop-service/src/main/java/com/intbyte/wizbuddy/shop/query/repository/ShopMapper.java
  wizbuddy-shop-service/src/main/resources/com/intbyte/wizbuddy/shop/query/repository/ShopMapper.xml
  wizbuddy-user-service/src/main/java/com/intbyte/wizbuddy/user/command/application/service/UserServiceImpl.java
  wizbuddy-user-service/src/main/java/com/intbyte/wizbuddy/user/command/domain/aggregate/vo/request/RequestRegisterUserVO.java
  wizbuddy-user-service/src/main/java/com/intbyte/wizbuddy/user/command/infrastructure/checklist/client/CheckListServiceClient.java
  wizbuddy-user-service/src/main/java/com/intbyte/wizbuddy/user/command/infrastructure/schedule/client/ScheduleServiceClient.java
  wizbuddy-user-service/src/main/java/com/intbyte/wizbuddy/user/command/infrastructure/schedule/dto/WeeklyScheduleDTO.java
  wizbuddy-user-service/src/main/java/com/intbyte/wizbuddy/user/command/infrastructure/schedule/vo/request/RequestModifyScheduleVO.java
  wizbuddy-user-service/src/main/java/com/intbyte/wizbuddy/user/command/infrastructure/schedule/vo/request/RequestRegistEmployeeWorkingPartVO.java
  wizbuddy-user-service/src/main/java/com/intbyte/wizbuddy/user/command/infrastructure/schedule/vo/request/RequestRegistWeeklyScheduleVO.java
  wizbuddy-user-service/src/main/java/com/intbyte/wizbuddy/user/command/infrastructure/schedule/vo/response/ResponseFindEmployeeWorkingPartVO.java
  wizbuddy-user-service/src/main/java/com/intbyte/wizbuddy/user/command/infrastructure/schedule/vo/response/ResponseModifyScheduleVO.java
  wizbuddy-user-service/src/main/java/com/intbyte/wizbuddy/user/command/infrastructure/schedule/vo/response/ResponseRegistEmployeeVO.java
  wizbuddy-user-service/src/main/java/com/intbyte/wizbuddy/user/command/infrastructure/schedule/vo/response/ResponseRegistWeeklyScheduleVO.java
  wizbuddy-user-service/src/main/java/com/intbyte/wizbuddy/user/command/infrastructure/service/InfraUserService.java
  wizbuddy-user-service/src/main/java/com/intbyte/wizbuddy/user/command/infrastructure/service/InfraUserServiceImpl.java
  wizbuddy-user-service/src/main/java/com/intbyte/wizbuddy/user/command/infrastructure/shop/client/ShopServiceClient.java
  wizbuddy-user-service/src/main/java/com/intbyte/wizbuddy/user/command/infrastructure/shop/dto/EmployeePerShopDTO.java
  wizbuddy-user-service/src/main/java/com/intbyte/wizbuddy/user/command/infrastructure/shop/dto/RequestEditShopDTO.java
  wizbuddy-user-service/src/main/java/com/intbyte/wizbuddy/user/command/infrastructure/shop/dto/RequestRegisterShopDTO.java
  wizbuddy-user-service/src/main/java/com/intbyte/wizbuddy/user/command/infrastructure/shop/dto/ShopDTO.java
  wizbuddy-user-service/src/main/java/com/intbyte/wizbuddy/user/command/infrastructure/shop/vo/request/RequestDeleteShopVO.java
  wizbuddy-user-service/src/main/java/com/intbyte/wizbuddy/user/command/infrastructure/shop/vo/request/RequestEditShopVO.java
  wizbuddy-user-service/src/main/java/com/intbyte/wizbuddy/user/command/infrastructure/shop/vo/request/RequestInsertEmployeePerShopVO.java
  wizbuddy-user-service/src/main/java/com/intbyte/wizbuddy/user/command/infrastructure/shop/vo/request/RequestRegisterShopVO.java
  wizbuddy-user-service/src/main/java/com/intbyte/wizbuddy/user/command/infrastructure/shop/vo/response/ResponseEditShopVO.java
  wizbuddy-user-service/src/main/java/com/intbyte/wizbuddy/user/command/infrastructure/shop/vo/response/ResponseInsertEmployeePerShopVO.java
  wizbuddy-user-service/src/main/java/com/intbyte/wizbuddy/user/command/infrastructure/shop/vo/response/ResponseRegisterShopVO.java
  wizbuddy-user-service/src/main/java/com/intbyte/wizbuddy/user/query/service/EmployerService.java
Labels: enhancement, fix

#196 shopservice websecurity http api 및 uri 수정
  wizbuddy-shop-service/src/main/java/com/intbyte/wizbuddy/security/WebSecurity.java
Labels: enhancement, fix
